# Generated by 03-tests.R
test_that("as_duckplyr_df() commutes for rename_with()", {
  # Data
  test_df <- data.frame(a = 1, b = 2)

  # Run
  pre <- test_df %>% as_duckplyr_df() %>% rename_with()
  post <- test_df %>% rename_with() %>% as_duckplyr_df()

  # Compare
  expect_equal(pre, post)
})
