# Generated by 03-tests.R
test_that("as_duckplyr_df() commutes for dplyr_reconstruct()", {
  # Data
  test_df <- data.frame(a = 1, b = 2)

  # Run
  pre <- test_df %>% as_duckplyr_df() %>% dplyr_reconstruct(test_df)
  post <- test_df %>% dplyr_reconstruct(test_df)

  # Compare
  expect_equal(pre, post)
})
