# Generated by 03-tests.R
test_that("as_duckplyr_df() commutes for group_modify()", {
  skip("Grouped")

  # Data
  test_df <- data.frame(a = 1, b = 2)

  # Run
  pre <- test_df %>% as_duckplyr_df() %>% group_modify(~ .x)
  post <- test_df %>% group_modify(~ .x) %>% as_duckplyr_df()

  # Compare
  expect_equal(pre, post)
})
