# Generated by 03-tests.R
test_that("as_duckplyr_df() commutes for slice_min()", {
  skip("External vector?")

  # Data
  test_df <- data.frame(a = 1, b = 2)

  # Run
  pre <- test_df %>% as_duckplyr_df() %>% slice_min("a")
  post <- test_df %>% slice_min("a") %>% as_duckplyr_df()

  # Compare
  expect_equal(pre, post)
})
