# Generated by 03-tests.R
test_that("as_duckplyr_df() commutes for sample_n()", {
  skip("Extra argument")

  # Data
  test_df <- data.frame(a = 1, b = 2)

  # Run
  pre <- test_df %>% as_duckplyr_df() %>% sample_n()
  post <- test_df %>% sample_n() %>% as_duckplyr_df()

  # Compare
  expect_equal(pre, post)
})
