# Generated by 03-tests.R
test_that("as_duckplyr_df() commutes for setequal()", {
  # Data
  test_df_x <- data.frame(a = 1, b = 2)
  test_df_y <- data.frame(a = 1, b = 2)

  # Run
  pre <- test_df_x %>% as_duckplyr_df() %>% setequal(test_df_y)
  post <- test_df_x %>% setequal(test_df_y)

  # Compare
  expect_equal(pre, post)
})
