# pak::pak("cynkra/constructive")
library(tidyverse)

dplyr <- asNamespace("dplyr")

s3_methods <- as_tibble(
  matrix(as.character(dplyr$.__NAMESPACE__.$S3methods), ncol = 4),
  .name_repair = ~ c("name", "class", "fun", "what")
)

df_methods <-
  s3_methods %>%
  filter(class == "data.frame") %>%
  # lazyeval methods, won't implement
  filter(!grepl("_$|^as[.]tbl$", name)) %>%
  # special dplyr methods, won't implement
  filter(!(name %in% c("dplyr_col_modify", "dplyr_row_slice"))) %>%
  mutate(is_tbl_return = !(name %in% c(
    "auto_copy", "group_indices", "group_size", "group_vars", "groups",
    "n_groups", "pull", "same_src", "setequal", "tbl_vars"
  ))) %>%
  mutate(code = unname(mget(fun, dplyr)))

first_line <- "# Generated by 03-tests.R"

get_test_code <- function(name, code, is_tbl_return) {
  formals <- formals(code)

  two_tables <- (length(formals) > 1) && (names(formals)[[2]] == "y")

  test_code_pre <- c(
    first_line,
    paste0('test_that("as_duckplyr_df() commutes for ', name, '()", {'),
    "  # Data"
  )

  if (two_tables) {
    test_code <- c(
      "  test_df_x <- data.frame(a = 1, b = 2)",
      "  test_df_y <- data.frame(a = 1, b = 2)",
      "",
      "  # Run",
      paste0(
        "  pre <- test_df_x %>% as_duckplyr_df() %>% ",
        name,
        "(test_df_y)"
      ),
      paste0(
        "  post <- test_df_x %>% ",
        name,
        "(test_df_y)",
        if (is_tbl_return) " %>% as_duckplyr_df()"
      )
    )
  } else {
    test_code <- c(
      "  test_df <- data.frame(a = 1, b = 2)",
      "",
      "  # Run",
      paste0(
        "  pre <- test_df %>% as_duckplyr_df() %>% ",
        name,
        "()"
      ),
      paste0(
        "  post <- test_df %>% ",
        name,
        "()",
        if (is_tbl_return) " %>% as_duckplyr_df()"
      )
    )
  }

  test_code_post <- c(
    "",
    "  # Compare",
    "  expect_equal(pre, post)",
    "})",
    ""
  )

  paste(c(test_code_pre, test_code, test_code_post), collapse = "\n")
}

old <-
  tibble(path = fs::dir_ls("tests/testthat", glob = "*.R")) %>%
  mutate(first_line = map_chr(path, brio::read_lines, 1)) %>%
  filter(first_line == !!first_line)

fs::file_delete(old$path)

tests <-
  df_methods %>%
  mutate(test_code = pmap(list(name, code, is_tbl_return), get_test_code))

tests %>%
  mutate(path = fs::path("tests", "testthat", paste0("test-", name, ".R"))) %>%
  select(text = test_code, path) %>%
  pwalk(brio::write_file)
