pkgload::load_all()

Sys.setenv(DUCKPLYR_FORCE = 1)

load("tools/tpch/001.rda")

customer <- as_duckplyr_df(customer)
lineitem <- as_duckplyr_df(lineitem)
nation <- as_duckplyr_df(nation)
orders <- as_duckplyr_df(orders)
part <- as_duckplyr_df(part)
partsupp <- as_duckplyr_df(partsupp)
region <- as_duckplyr_df(region)
supplier <- as_duckplyr_df(supplier)

tpch_01()
tpch_02()
tpch_03()
tpch_04()
tpch_05()
tpch_06()
tpch_07()
tpch_08()
tpch_09()
tpch_10()
tpch_11()
tpch_12()
tpch_13()
tpch_14()
tpch_15()
tpch_16()
tpch_17()
tpch_18()
tpch_19()
tpch_20()
tpch_21()
tpch_22()
