pkgload::load_all()

Sys.setenv(DUCKPLYR_FORCE = TRUE)

load("tools/tpch/001.rda")

customer <- as_duckplyr_df(customer)
lineitem <- as_duckplyr_df(lineitem)
nation <- as_duckplyr_df(nation)
orders <- as_duckplyr_df(orders)
part <- as_duckplyr_df(part)
partsupp <- as_duckplyr_df(partsupp)
region <- as_duckplyr_df(region)
supplier <- as_duckplyr_df(supplier)

invisible(tpch_01())
invisible(tpch_02())
invisible(tpch_03())
invisible(tpch_04())
invisible(tpch_05())
invisible(tpch_06())
invisible(tpch_07())
invisible(tpch_08())
invisible(tpch_09())
invisible(tpch_10())
invisible(tpch_11())
invisible(tpch_12())
invisible(tpch_13())
invisible(tpch_14())
invisible(tpch_15())
invisible(tpch_16())
invisible(tpch_17())
invisible(tpch_18())
invisible(tpch_19())
invisible(tpch_20())
invisible(tpch_21())
invisible(tpch_22())

meta_replay_to_file("tools/38-tpch-raw.R", 'load("tools/tpch/001.rda")')
