pre <- 'library(touchstone)

source("tools/30-tpch-export.R")
source("tools/31-tpch-load-qs.R")

branch_install()

'

header <- paste0("# Generated by 60-touchstone-gen.R, ", "do not edit by hand\n\n")

body <- function(sf, test) paste0('benchmark_run(
  expr_before_benchmark = {
    library(duckplyr)
    data <- qs::qread("tools/tpch/', sf, '.qs")
    .mapply(assign, list(names(data), data), list(pos = .GlobalEnv))

    customer <- as_duckplyr_df(customer)
    lineitem <- as_duckplyr_df(lineitem)
    nation <- as_duckplyr_df(nation)
    orders <- as_duckplyr_df(orders)
    part <- as_duckplyr_df(part)
    partsupp <- as_duckplyr_df(partsupp)
    region <- as_duckplyr_df(region)
    supplier <- as_duckplyr_df(supplier)
  },
  `', sf, '_tpch_', test, '` = nrow(duckplyr:::tpch_', test, '()),
  n = 10
)\n\n')

footer <- 'benchmark_analyze()'

code <- paste0(
  header,
  pre,
  body("001", "01"),
  footer
)

writeLines(code, "touchstone/script.R")
