library(tidyverse)

pre <- 'library(touchstone)

source("tools/30-tpch-export.R")
source("tools/31-tpch-load-qs.R")

branch_install()

'

header <- paste0(
  "# Generated by 70-touchstone-gen.R, ",
  "do not edit by hand\n\n"
)

body <- function(sf, test, n) {
  glue::glue(
    'benchmark_run(
  expr_before_benchmark = {{
    library(duckplyr)
    for (table in c(
      "customer",
      "lineitem",
      "nation",
      "orders",
      "part",
      "partsupp",
      "region",
      "supplier"
    )) {{
      assign(
        table,
        as_duckdb_tibble(
          qs2::qs_read(file.path("tools/tpch/{sf}", paste0(table, ".qs")))
        ),
        envir = .GlobalEnv
      )
    }}
  }},
  `{sf}_tpch_{test}` = collect(duckplyr:::tpch_{test}()),
  n = {n}
)\n\n'
  )
}

footer <- 'benchmark_analyze()'

bodies <-
  crossing(
    tibble(
      n = c(3, 10, 30),
      sf = c("100", "010", "001")
    ),
    test = c(
      "01",
      "02",
      "03",
      "04",
      "05",
      "06",
      "07",
      "08",
      "09",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
      "21",
      "22"
    ),
  ) |>
  rowwise() |>
  mutate(code = body(sf, test, n)) |>
  ungroup() |>
  summarize(
    code = paste(code, collapse = "\n")
  ) |>
  pull(code)

code <- paste0(
  header,
  pre,
  bodies,
  footer
)

writeLines(code, "touchstone/script.R")
