# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr add_count
#' @export
add_count.duckplyr_df <- function(x, ..., wt = NULL, sort = FALSE, name = NULL, .drop = deprecated()) {
  # Our implementation
  force(x)
  out <- NextMethod()
  out <- dplyr_reconstruct(out, x)
  return(out)

  # dplyr implementation
  out <- add_count_impl(
    x,
    ...,
    wt = {{ wt }},
    sort = sort,
    name = name,
    .drop = .drop
  )
  dplyr_reconstruct(out, x)
}

duckplyr_add_count <- function(x, ...) {
  if (!identical(class(x), "data.frame") && !identical(class(x), c("tbl_df", "tbl", "data.frame"))) {
    testthat::skip("`add_count()` only supported for plain data frames or tibbles")
  }

  x <- as_duckplyr_df(x)
  out <- add_count(x, ...)
  class(out) <- setdiff(class(out), "duckplyr_df")
  out
}
