# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr add_count
#' @export
add_count.duckplyr_df <- function(x, ..., wt = NULL, sort = FALSE, name = NULL, .drop = deprecated()) {
  # Our implementation
  rel_try(
    "No relational implementation for add_count()" = TRUE,
    {
      return(out)
    }
  )

  # dplyr forward
  x_df <- x
  class(x_df) <- setdiff(class(x_df), "duckplyr_df")
  out <- add_count(x_df, ..., wt = {{ wt }}, sort = sort, name = name, .drop = .drop)
  out <- dplyr_reconstruct(out, x)
  return(out)

  # dplyr implementation
  out <- add_count_impl(
    x,
    ...,
    wt = {{ wt }},
    sort = sort,
    name = name,
    .drop = .drop
  )
  dplyr_reconstruct(out, x)
}

duckplyr_add_count <- function(x, ...) {
  try_fetch(
    x <- as_duckplyr_df(x),
    error = function(e) {
      testthat::skip(conditionMessage(e))
    }
  )
  out <- add_count(x, ...)
  class(out) <- setdiff(class(out), "duckplyr_df")
  out
}
