# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr anti_join
#' @export
anti_join.duckplyr_df <- function(x, y, by = NULL, copy = FALSE, ..., na_matches = c("na", "never")) {
  # Our implementation
  force(x)
  out <- NextMethod()
  out <- dplyr_reconstruct(out, x)
  return(out)

  # dplyr implementation
  y <- auto_copy(x, y, copy = copy)
  join_filter(x, y, by = by, type = "anti", na_matches = na_matches, user_env = caller_env())
}

duckplyr_anti_join <- function(.data, ...) {
  if (is_grouped_df(.data)) {
    testthat::skip("`anti_join()` not supported for grouped_df")
  }

  if (inherits(.data, "rowwise_df")) {
    testthat::skip("`anti_join()` not supported for rowwise_df")
  }

  .data <- as_duckplyr_df(.data)
  out <- anti_join(.data, ...)
  class(out) <- setdiff(class(out), "duckplyr_df")
  out
}
