# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr auto_copy
#' @export
auto_copy.duckplyr_df <- function(x, y, copy = FALSE, ...) {
  return(as_duckplyr_df(y))

  # dplyr implementation
  as.data.frame(y)
}

duckplyr_auto_copy <- function(x, y, ...) {
  try_fetch(
    {
      x <- as_duckplyr_df(x)
      y <- as_duckplyr_df(y)
    },
    error = function(e) {
      testthat::skip(conditionMessage(e))
    }
  )
  out <- auto_copy(x, y, ...)
  out
}
