# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr collect
#' @export
collect.duckplyr_df <- function(x, ...) {
  # Our implementation
  rel_try(
    "No relational implementation for collect()" = TRUE,
    {
      return(out)
    }
  )

  # dplyr forward
  x_df <- x
  class(x_df) <- setdiff(class(x_df), "duckplyr_df")
  collect <- dplyr:::collect.data.frame
  out <- collect(x_df, ...)
  out <- dplyr_reconstruct(out, x)
  return(out)

  # dplyr implementation
  x
}

duckplyr_collect <- function(x, ...) {
  try_fetch(
    x <- as_duckplyr_df(x),
    error = function(e) {
      testthat::skip(conditionMessage(e))
    }
  )
  out <- collect(x, ...)
  class(out) <- setdiff(class(out), "duckplyr_df")
  out
}
