# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr distinct
#' @export
distinct.duckplyr_df <- function(.data, ..., .keep_all = FALSE) {
  # Our implementation
  rel_try(
    "distinct(.keep_all = TRUE) not supported for relational" = .keep_all,
    {
      dots <- enquos(..., .named = TRUE)

      # FIXME: avoid column duplication in a cleaner way
      dupes <- duplicated(names(dots), fromLast = TRUE)
      dots <- dots[!dupes]

      exprs <- rel_translate_dots(dots[!dupes], .data)
      rel <- duckdb_rel_from_df(.data)
      if (length(exprs) > 0) {
        rel <- rel_project(rel, exprs)
      }
      out_rel <- rel_distinct(rel)
      out <- rel_to_df(out_rel)
      out <- dplyr_reconstruct(out, .data)
      return(out)
    }
  )

  # dplyr forward
  x_df <- .data
  class(x_df) <- setdiff(class(x_df), "duckplyr_df")
  distinct <- dplyr:::distinct.data.frame
  out <- distinct(x_df, ..., .keep_all = .keep_all)
  out <- dplyr_reconstruct(out, .data)
  return(out)

  # dplyr implementation
  prep <- distinct_prepare(
    .data,
    vars = enquos(...),
    group_vars = group_vars(.data),
    .keep_all = .keep_all,
    caller_env = caller_env()
  )

  out <- prep$data

  cols <- dplyr_col_select(out, prep$vars)
  loc <- vec_unique_loc(cols)

  out <- dplyr_col_select(out, prep$keep)
  dplyr_row_slice(out, loc)
}

duckplyr_distinct <- function(.data, ...) {
  try_fetch(
    .data <- as_duckplyr_df(.data),
    error = function(e) {
      testthat::skip(conditionMessage(e))
    }
  )
  out <- distinct(.data, ...)
  class(out) <- setdiff(class(out), "duckplyr_df")
  out
}
