# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr dplyr_reconstruct
#' @export
dplyr_reconstruct.duckplyr_df <- function(data, template) {
  #
  force(data)
  out <- NextMethod()
  return(out)
}
