# Generated by 02-duckplyr_df-methods.R

# Avoid harmful stripping of attributes in base implementation
dplyr_reconstruct <- function(data, template) {
  UseMethod("dplyr_reconstruct", template)
}

#' @export
dplyr_reconstruct.duckplyr_df <- function(data, template) {
  # Our implementation
  .Call(copy_df_attribs, data, template)
  return(data)

  # dplyr implementation
  attrs <- attributes(template)
  attrs$names <- names(data)
  attrs$row.names <- .row_names_info(data, type = 0L)

  attributes(data) <- attrs
  data
}

duckplyr_dplyr_reconstruct <- function(data, ...) {
  if (!identical(class(data), "data.frame") && !identical(class(data), c("tbl_df", "tbl", "data.frame"))) {
    testthat::skip("`dplyr_reconstruct()` only supported for plain data frames or tibbles")
  }

  data <- as_duckplyr_df(data)
  out <- dplyr_reconstruct(data, ...)
  out
}
