# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr dplyr_reconstruct
#' @export
dplyr_reconstruct.duckplyr_df <- function(data, template) {
  # Our implementation
  force(data)
  out <- NextMethod()
  return(out)

  # dplyr implementation
  attrs <- attributes(template)
  attrs$names <- names(data)
  attrs$row.names <- .row_names_info(data, type = 0L)

  attributes(data) <- attrs
  data
}

duckplyr_dplyr_reconstruct <- function(.data, ...) {
  .data <- as_duckplyr_df(.data)
  out <- dplyr_reconstruct(.data, ...)
  out
}
