check_filter <- dplyr:::check_filter
check_keep <- dplyr:::check_keep
check_name <- dplyr:::check_name
check_na_matches <- dplyr:::check_na_matches
check_string <- dplyr:::check_string
check_transmute_args <- dplyr:::check_transmute_args
count_regroups <- dplyr:::count_regroups
dplyr_error_call <- dplyr:::dplyr_error_call
dplyr_local_error_call <- dplyr:::dplyr_local_error_call
dplyr_quosures <- dplyr:::dplyr_quosures
eval_relocate <- dplyr:::eval_relocate
eval_select_by <- dplyr:::eval_select_by
group_by_drop_default <- dplyr:::group_by_drop_default
some <- dplyr:::some
