#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @import rlang
#' @importFrom dplyr across
#' @importFrom dplyr add_tally
#' @importFrom dplyr case_when
#' @importFrom dplyr collapse
#' @importFrom dplyr collect
#' @importFrom dplyr compute
#' @importFrom dplyr count
#' @importFrom dplyr desc
#' @importFrom dplyr dplyr_col_modify
#' @importFrom dplyr dplyr_row_slice
#' @importFrom dplyr funs
#' @importFrom dplyr funs_
#' @importFrom dplyr group_by
#' @importFrom dplyr group_data
#' @importFrom dplyr group_keys
#' @importFrom dplyr group_rows
#' @importFrom dplyr group_size
#' @importFrom dplyr is_grouped_df
#' @importFrom dplyr join_by
#' @importFrom dplyr lead
#' @importFrom dplyr mutate_all
#' @importFrom dplyr n
#' @importFrom dplyr rename_all
#' @importFrom dplyr rename_at
#' @importFrom dplyr rename_if
#' @importFrom dplyr row_number
#' @importFrom dplyr rowwise
#' @importFrom dplyr same_src
#' @importFrom dplyr select_all
#' @importFrom dplyr select_at
#' @importFrom dplyr select_if
#' @importFrom dplyr slice_head
#' @importFrom dplyr slice_max
#' @importFrom dplyr slice_min
#' @importFrom dplyr slice_sample
#' @importFrom dplyr slice_tail
#' @importFrom dplyr summarise_all
#' @importFrom dplyr summarise_at
#' @importFrom dplyr tally
#' @importFrom dplyr vars
#' @importFrom dplyr with_groups
#' @importFrom glue glue
#' @importFrom lifecycle deprecated
#' @importFrom purrr imap
#' @importFrom purrr map
#' @importFrom purrr map_chr
#' @importFrom purrr map_lgl
#' @importFrom purrr map2
#' @importFrom purrr pmap
#' @importFrom purrr reduce
#' @importFrom tibble as_tibble
#' @importFrom tibble deframe
#' @importFrom tibble new_tibble
#' @importFrom tibble tibble
#' @importFrom tidyselect everything
#' @importFrom vctrs list_of
#' @importFrom vctrs new_data_frame
#' @importFrom vctrs new_rcrd
#' @importFrom vctrs vec_c
#' @importFrom vctrs vec_cbind
#' @importFrom vctrs vec_rbind
#' @importFrom vctrs vec_slice
#' @useDynLib duckplyr, .registration = TRUE
## usethis namespace: end
NULL
