# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr full_join
#' @export
full_join.duckplyr_df <- function(x, y, by = NULL, copy = FALSE, suffix = c(".x", ".y"), ..., keep = NULL, na_matches = c("na", "never"), multiple = NULL) {
  # Our implementation
  force(x)
  out <- NextMethod()
  out <- dplyr_reconstruct(out, x)
  return(out)

  # dplyr implementation
  y <- auto_copy(x, y, copy = copy)
  join_mutate(
    x = x,
    y = y,
    by = by,
    type = "full",
    suffix = suffix,
    na_matches = na_matches,
    keep = keep,
    multiple = multiple,
    # All keys from both inputs are retained. Erroring never makes sense.
    unmatched = "drop",
    user_env = caller_env()
  )
}

duckplyr_full_join <- function(x, y, ...) {
  if (!identical(class(x), "data.frame") && !identical(class(x), c("tbl_df", "tbl", "data.frame"))) {
    testthat::skip("`full_join()` only supported for plain data frames or tibbles")
  }

  x <- as_duckplyr_df(x)
  y <- as_duckplyr_df(y)
  out <- full_join(x, y, ...)
  class(out) <- setdiff(class(out), "duckplyr_df")
  out
}
