# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr full_join
#' @export
full_join.duckplyr_df <- function(x, y, by = NULL, copy = FALSE, suffix = c(".x", ".y"), ..., keep = NULL, na_matches = c("na", "never"), multiple = NULL) {
  check_dots_empty0(...)
  error_call <- caller_env()

  # Our implementation
  rel_try(
    "Only equi-joins for full_join()" = inherits(by, "dplyr_join_by") && any(by$condition != "=="),
    "No implicit cross joins for full_join()" = is_cross_by(by),
    "No relational implementation for full_join(copy = TRUE)" = copy,
    {
      out <- rel_join_impl(x, y, by, suffix, keep, na_matches, "full", error_call)
      return(out)
    }
  )

  # dplyr forward
  full_join <- dplyr:::full_join.data.frame
  out <- full_join(x, y, by, copy, suffix, ..., keep = keep, na_matches = na_matches, multiple = multiple)
  return(out)

  # dplyr implementation
  check_dots_empty0(...)
  y <- auto_copy(x, y, copy = copy)
  join_mutate(
    x = x,
    y = y,
    by = by,
    type = "full",
    suffix = suffix,
    na_matches = na_matches,
    keep = keep,
    multiple = multiple,
    # All keys from both inputs are retained. Erroring never makes sense.
    unmatched = "drop",
    user_env = caller_env()
  )
}

duckplyr_full_join <- function(x, y, ...) {
  try_fetch(
    {
      x <- as_duckplyr_df(x)
      y <- as_duckplyr_df(y)
    },
    error = function(e) {
      testthat::skip(conditionMessage(e))
    }
  )
  out <- full_join(x, y, ...)
  class(out) <- setdiff(class(out), "duckplyr_df")
  out
}
