# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr group_indices
#' @export
group_indices.duckplyr_df <- function(.data, ...) {
  # Our implementation
  force(.data)
  out <- NextMethod()
  return(out)

  # dplyr implementation
  if (dots_n(...) > 0) {
    lifecycle::deprecate_warn(
      "1.0.0", "group_indices(... = )",
      details = "Please `group_by()` first",
      always = TRUE
    )
    .data <- group_by(.data, ...)
  }

  .Call(`dplyr_group_indices`, .data, group_rows(.data))
}

duckplyr_group_indices <- function(.data, ...) {
  if (is_grouped_df(.data)) {
    testthat::skip("`group_indices()` not supported for grouped_df")
  }

  if (inherits(.data, "rowwise_df")) {
    testthat::skip("`group_indices()` not supported for rowwise_df")
  }

  .data <- as_duckplyr_df(.data)
  out <- group_indices(.data, ...)
  out
}
