# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr group_vars
#' @export
group_vars.duckplyr_df <- function(x) {
  # Our implementation
  force(x)
  out <- NextMethod()
  return(out)

  # dplyr implementation
  setdiff(names(group_data(x)), ".rows")
}

duckplyr_group_vars <- function(x, ...) {
  if (!identical(class(x), "data.frame") && !identical(class(x), c("tbl_df", "tbl", "data.frame"))) {
    testthat::skip("`group_vars()` only supported for plain data frames or tibbles")
  }

  x <- as_duckplyr_df(x)
  out <- group_vars(x, ...)
  out
}
