# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr group_modify
#' @export
group_modify.duckplyr_df <- function(.data, .f, ..., .keep = FALSE, keep = deprecated()) {
  # Our implementation
  x_df <- .data
  class(x_df) <- setdiff(class(x_df), "duckplyr_df")
  out <- group_modify(x_df, .f, ..., .keep = .keep, keep = keep)
  out <- dplyr_reconstruct(out, .data)
  return(out)

  # dplyr implementation
  if (!missing(keep)) {
    lifecycle::deprecate_warn("1.0.0", "group_modify(keep = )", "group_modify(.keep = )", always = TRUE)
    .keep <- keep
  }
  .f <- as_group_map_function(.f)
  .f(.data, group_keys(.data), ...)
}

duckplyr_group_modify <- function(.data, ...) {
  try_fetch(
    .data <- as_duckplyr_df(.data),
    error = function(e) {
      testthat::skip(conditionMessage(e))
    }
  )
  out <- group_modify(.data, ...)
  class(out) <- setdiff(class(out), "duckplyr_df")
  out
}
