# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr group_keys
#' @export
group_keys.duckplyr_df <- function(.tbl, ...) {
  # Our implementation
  rel_try(
    "No relational implementation for group_keys()" = TRUE,
    {
      return(out)
    }
  )

  # dplyr forward
  x_df <- .tbl
  class(x_df) <- setdiff(class(x_df), "duckplyr_df")
  out <- group_keys(x_df, ...)
  out <- dplyr_reconstruct(out, .tbl)
  return(out)

  # dplyr implementation
  if (dots_n(...) > 0) {
    lifecycle::deprecate_warn(
      "1.0.0", "group_keys(... = )",
      details = "Please `group_by()` first",
      always = TRUE
    )
    .tbl <- group_by(.tbl, ...)
  }
  out <- group_data(.tbl)
  group_keys0(out)
}

duckplyr_group_keys <- function(.tbl, ...) {
  try_fetch(
    .tbl <- as_duckplyr_df(.tbl),
    error = function(e) {
      testthat::skip(conditionMessage(e))
    }
  )
  out <- group_keys(.tbl, ...)
  class(out) <- setdiff(class(out), "duckplyr_df")
  out
}
