# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr group_by
#' @export
group_by.duckplyr_df <- function(.data, ..., .add = FALSE, .drop = group_by_drop_default(.data)) {
  # dplyr forward
  x_df <- .data
  class(x_df) <- setdiff(class(x_df), "duckplyr_df")
  out <- group_by(x_df, ..., .add = .add, .drop = .drop)
  out <- dplyr_reconstruct(out, .data)
  return(out)

  # dplyr implementation
  groups <- group_by_prepare(
    .data,
    ...,
    .add = .add,
    error_call = current_env()
  )
  grouped_df(groups$data, groups$group_names, .drop)
}

duckplyr_group_by <- function(.data, ...) {
  testthat::skip("`group_by()` not supported for duckplyr")
}
