# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr group_data
#' @export
group_data.duckplyr_df <- function(.data) {
  # Our implementation
  force(.data)
  out <- NextMethod()
  out <- dplyr_reconstruct(out, .data)
  return(out)

  # dplyr implementation
  rows <- new_list_of(list(seq_len(nrow(.data))), ptype = integer())
  new_data_frame(list(.rows = rows), n = 1L)
}

duckplyr_group_data <- function(.data, ...) {
  if (!identical(class(.data), "data.frame") && !identical(class(.data), c("tbl_df", "tbl", "data.frame"))) {
    testthat::skip("`group_data()` only supported for plain data frames or tibbles")
  }

  .data <- as_duckplyr_df(.data)
  out <- group_data(.data, ...)
  class(out) <- setdiff(class(out), "duckplyr_df")
  out
}
