# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr group_vars
#' @export
group_vars.duckplyr_df <- function(x) {
  character()
}

duckplyr_group_vars <- function(x, ...) {
  try_fetch(
    x <- as_duckplyr_df(x),
    error = function(e) {
      testthat::skip(conditionMessage(e))
    }
  )
  out <- group_vars(x, ...)
  out
}
