# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr group_trim
#' @export
group_trim.duckplyr_df <- function(.tbl, .drop = group_by_drop_default(.tbl)) {
  # dplyr forward
  x_df <- .tbl
  class(x_df) <- setdiff(class(x_df), "duckplyr_df")
  out <- group_trim(x_df, .drop)
  out <- dplyr_reconstruct(out, .tbl)
  return(out)

  # dplyr implementation
  .tbl
}

duckplyr_group_trim <- function(.tbl, ...) {
  try_fetch(
    .tbl <- as_duckplyr_df(.tbl),
    error = function(e) {
      testthat::skip(conditionMessage(e))
    }
  )
  out <- group_trim(.tbl, ...)
  class(out) <- setdiff(class(out), "duckplyr_df")
  out
}
