# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr group_size
#' @export
group_size.duckplyr_df <- function(x) {
  # Our implementation
  x_df <- x
  class(x_df) <- setdiff(class(x_df), "duckplyr_df")
  out <- group_size(x_df)
  return(out)

  # dplyr implementation
  lengths(group_rows(x))
}

duckplyr_group_size <- function(x, ...) {
  try_fetch(
    x <- as_duckplyr_df(x),
    error = function(e) {
      testthat::skip(conditionMessage(e))
    }
  )
  out <- group_size(x, ...)
  out
}
