# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr groups
#' @export
groups.duckplyr_df <- function(x) {
  # Our implementation
  force(x)
  out <- NextMethod()
  return(out)

  # dplyr implementation
  syms(group_vars(x))
}
