# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr inner_join
#' @export
inner_join.duckplyr_df <- function(x, y, by = NULL, copy = FALSE, suffix = c(".x", ".y"), ..., keep = NULL, na_matches = c("na", "never"), multiple = NULL, unmatched = "drop") {
  check_dots_empty0(...)
  error_call <- caller_env()

  # Our implementation
  rel_try(
    "Only equi-joins for inner_join()" = inherits(by, "dplyr_join_by") && any(by$condition != "=="),
    "No implicit cross joins for inner_join()" = is_cross_by(by),
    "No relational implementation for inner_join(copy = TRUE)" = copy,
    {
      out <- rel_join_impl(x, y, by, suffix, keep, na_matches, "inner", error_call)
      return(out)
    }
  )

  # dplyr forward
  x_df <- x
  class(x_df) <- setdiff(class(x_df), "duckplyr_df")
  inner_join <- dplyr:::inner_join.data.frame
  out <- inner_join(x_df, y, by, copy, suffix, ..., keep = keep, na_matches = na_matches, multiple = multiple, unmatched = unmatched)
  out <- dplyr_reconstruct(out, x)
  return(out)

  # dplyr implementation
  check_dots_empty0(...)
  y <- auto_copy(x, y, copy = copy)
  join_mutate(
    x = x,
    y = y,
    by = by,
    type = "inner",
    suffix = suffix,
    na_matches = na_matches,
    keep = keep,
    multiple = multiple,
    unmatched = unmatched,
    user_env = caller_env()
  )
}

duckplyr_inner_join <- function(x, y, ...) {
  try_fetch(
    {
      x <- as_duckplyr_df(x)
      y <- as_duckplyr_df(y)
    },
    error = function(e) {
      testthat::skip(conditionMessage(e))
    }
  )
  out <- inner_join(x, y, ...)
  class(out) <- setdiff(class(out), "duckplyr_df")
  out
}
