# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr mutate
#' @export
mutate.duckplyr_df <- function(.data, ..., .by = NULL, .keep = c("all", "used", "unused", "none"), .before = NULL, .after = NULL) {
  by <- enquo(.by)
  before <- enquo(.before)
  after <- enquo(.after)
  .keep <- arg_match(.keep)

  # Our implementation
  rel_try(
    "No relational implementation for windowed mutate()" = !quo_is_null(by),
    "No relational implementation for non-NULL .before" = !quo_is_null(before),
    "No relational implementation for non-NULL .after" = !quo_is_null(after),
    "No relational implementation for non-all .keep" = (.keep != "all"),
    {
      rel <- duckdb_rel_from_df(.data)
      dots <- dplyr_quosures(...)

      out <- rel_to_df(rel)

      # FIXME: use fewer projections
      for (i in seq_along(dots)) {
        new <- names(dots)[[i]]
        new_pos <- match(new, names(out), nomatch = length(out) + 1L)
        exprs <- imap(set_names(names(out)), relexpr_reference, rel = NULL)
        exprs[[new_pos]] <- rel_translate(dots[[i]], out, alias = new)
        rel <- rel_project(rel, exprs)
        out <- rel_to_df(rel)
      }

      out <- dplyr_reconstruct(out, .data)
      return(out)
    }
  )

  # dplyr forward
  x_df <- .data
  class(x_df) <- setdiff(class(x_df), "duckplyr_df")
  out <- mutate(x_df, ..., .by = {{ .by }}, .keep = .keep, .before = {{ .before }}, .after = {{ .after }})
  out <- dplyr_reconstruct(out, .data)
  return(out)

  # dplyr implementation
  keep <- arg_match(.keep)

  by <- compute_by({{ .by }}, .data, by_arg = ".by", data_arg = ".data")

  cols <- mutate_cols(.data, dplyr_quosures(...), by)
  used <- attr(cols, "used")

  out <- dplyr_col_modify(.data, cols)

  names_original <- names(.data)

  out <- mutate_relocate(
    out = out,
    before = {{ .before }},
    after = {{ .after }},
    names_original = names_original
  )

  names_new <- names(cols)
  names_groups <- by$names

  out <- mutate_keep(
    out = out,
    keep = keep,
    used = used,
    names_new = names_new,
    names_groups = names_groups
  )

  out
}

duckplyr_mutate <- function(.data, ...) {
  try_fetch(
    .data <- as_duckplyr_df(.data),
    error = function(e) {
      testthat::skip(conditionMessage(e))
    }
  )
  out <- mutate(.data, ...)
  class(out) <- setdiff(class(out), "duckplyr_df")
  out
}
