# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr nest_by
#' @export
nest_by.duckplyr_df <- function(.data, ..., .key = "data", .keep = FALSE) {
  # Our implementation
  force(.data)
  out <- NextMethod()
  out <- dplyr_reconstruct(out, .data)
  return(out)

  # dplyr implementation
  .data <- group_by(.data, ...)
  nest_by.grouped_df(.data, .key = .key, .keep = .keep)
}

duckplyr_nest_by <- function(.data, ...) {
  if (!identical(class(.data), "data.frame") && !identical(class(.data), c("tbl_df", "tbl", "data.frame"))) {
    testthat::skip("`nest_by()` only supported for plain data frames or tibbles")
  }

  .data <- as_duckplyr_df(.data)
  out <- nest_by(.data, ...)
  class(out) <- setdiff(class(out), "duckplyr_df")
  out
}
