# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr pull
#' @export
pull.duckplyr_df <- function(.data, var = -1, name = NULL, ...) {
  # Our implementation
  force(.data)
  out <- NextMethod()
  return(out)

  # dplyr implementation
  var <- tidyselect::vars_pull(names(.data), !!enquo(var))
  name <- enquo(name)
  if (quo_is_null(name)) {
    return(.data[[var]])
  }
  name <- tidyselect::vars_pull(names(.data), !!name)
  set_names(.data[[var]], nm = .data[[name]])
}

duckplyr_pull <- function(.data, ...) {
  if (!identical(class(.data), "data.frame") && !identical(class(.data), c("tbl_df", "tbl", "data.frame"))) {
    testthat::skip("`pull()` only supported for plain data frames or tibbles")
  }

  .data <- as_duckplyr_df(.data)
  out <- pull(.data, ...)
  out
}
