# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr pull
#' @export
pull.duckplyr_df <- function(.data, var = -1, name = NULL, ...) {
  # Our implementation
  force(.data)
  out <- NextMethod(var = {{ var }}, name = {{ name }})
  return(out)

  # dplyr implementation
  var <- tidyselect::vars_pull(names(.data), !!enquo(var))
  name <- enquo(name)
  if (quo_is_null(name)) {
    return(.data[[var]])
  }
  name <- tidyselect::vars_pull(names(.data), !!name)
  set_names(.data[[var]], nm = .data[[name]])
}

duckplyr_pull <- function(.data, ...) {
  try_fetch(
    .data <- as_duckplyr_df(.data),
    error = function(e) {
      testthat::skip(conditionMessage(e))
    }
  )
  out <- pull(.data, ...)
  out
}
