# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr relocate
#' @export
relocate.duckplyr_df <- function(.data, ..., .before = NULL, .after = NULL) {
  # Our implementation
  force(.data)
  out <- NextMethod()
  out <- dplyr_reconstruct(out, .data)
  return(out)
}
