# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr rename_with
#' @export
rename_with.duckplyr_df <- function(.data, .fn, .cols = everything(), ...) {
  # Our implementation
  force(.data)
  out <- NextMethod()
  out <- dplyr_reconstruct(out, .data)
  return(out)
}
