# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr right_join
#' @export
right_join.duckplyr_df <- function(x, y, by = NULL, copy = FALSE, suffix = c(".x", ".y"), ..., keep = NULL, na_matches = c("na", "never"), multiple = NULL, unmatched = "drop") {
  # Our implementation
  force(x)
  out <- NextMethod()
  out <- dplyr_reconstruct(out, x)
  return(out)

  # dplyr implementation
  y <- auto_copy(x, y, copy = copy)
  join_mutate(
    x = x,
    y = y,
    by = by,
    type = "right",
    suffix = suffix,
    na_matches = na_matches,
    keep = keep,
    multiple = multiple,
    unmatched = unmatched,
    user_env = caller_env()
  )
}

duckplyr_right_join <- function(.data, ...) {
  .data <- as_duckplyr_df(.data)
  out <- right_join(.data, ...)
  class(out) <- setdiff(class(out), "duckplyr_df")
  out
}
