# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr rows_append
#' @export
rows_append.duckplyr_df <- function(x, y, ..., copy = FALSE, in_place = FALSE) {
  # dplyr forward
  x_df <- x
  class(x_df) <- setdiff(class(x_df), "duckplyr_df")
  out <- rows_append(x_df, y, ..., copy = copy, in_place = in_place)
  out <- dplyr_reconstruct(out, x)
  return(out)

  # dplyr implementation
  check_dots_empty()
  rows_df_in_place(in_place)

  y <- auto_copy(x, y, copy = copy)

  rows_check_containment(x, y)
  y <- rows_cast_y(y, x)

  rows_bind(x, y)
}

duckplyr_rows_append <- function(x, y, ...) {
  try_fetch(
    {
      x <- as_duckplyr_df(x)
      y <- as_duckplyr_df(y)
    },
    error = function(e) {
      testthat::skip(conditionMessage(e))
    }
  )
  out <- rows_append(x, y, ...)
  class(out) <- setdiff(class(out), "duckplyr_df")
  out
}
