# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr rowwise
#' @export
rowwise.duckplyr_df <- function(data, ...) {
  # Our implementation
  force(data)
  out <- NextMethod()
  out <- dplyr_reconstruct(out, data)
  return(out)

  # dplyr implementation
  vars <- tidyselect::eval_select(expr(c(...)), data)
  rowwise_df(data, vars)
}

duckplyr_rowwise <- function(.data, ...) {
  if (is_grouped_df(.data)) {
    testthat::skip("`rowwise()` not supported for grouped_df")
  }

  if (inherits(.data, "rowwise_df")) {
    testthat::skip("`rowwise()` not supported for rowwise_df")
  }

  .data <- as_duckplyr_df(.data)
  out <- rowwise(.data, ...)
  class(out) <- setdiff(class(out), "duckplyr_df")
  out
}
