# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr rowwise
#' @export
rowwise.duckplyr_df <- function(data, ...) {
  # Our implementation
  force(data)
  out <- NextMethod()
  out <- dplyr_reconstruct(out, data)
  return(out)

  # dplyr implementation
  vars <- tidyselect::eval_select(expr(c(...)), data)
  rowwise_df(data, vars)
}

duckplyr_rowwise <- function(.data, ...) {
  testthat::skip("`rowwise()` not supported for duckplyr")
}
