# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr same_src
#' @export
same_src.duckplyr_df <- function(x, y) {
  # Our implementation
  force(x)
  out <- NextMethod()
  return(out)

  # dplyr implementation
  is.data.frame(y)
}

duckplyr_same_src <- function(x, y, ...) {
  try_fetch(
    {
      x <- as_duckplyr_df(x)
      y <- as_duckplyr_df(y)
    },
    error = function(e) {
      testthat::skip(conditionMessage(e))
    }
  )
  out <- same_src(x, y, ...)
  out
}
