# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr select
#' @export
select.duckplyr_df <- function(.data, ...) {
  # Our implementation
  force(.data)
  out <- NextMethod()
  out <- dplyr_reconstruct(out, .data)
  return(out)

  # dplyr implementation
  # duckplyr: Common code
  error_call <- dplyr_error_call()

  loc <- tidyselect::eval_select(
    expr(c(...)),
    data = .data,
    error_call = error_call
  )
  loc <- ensure_group_vars(loc, .data, notify = TRUE)

  # duckplyr: Backend-specific
  out <- dplyr_col_select(.data, loc)
  out <- set_names(out, names(loc))

  out
}
