# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr setequal
#' @export
setequal.duckplyr_df <- function(x, y, ...) {
  # Our implementation
  force(x)
  out <- NextMethod()
  return(out)

  # dplyr implementation
  check_dots_empty()
  if (!is.data.frame(y)) {
    abort("`y` must be a data frame.")
  }
  if (!isTRUE(is_compatible(x, y))) {
    return(FALSE)
  }

  cast <- vec_cast_common(x = x, y = y)
  all(vec_in(cast$x, cast$y)) && all(vec_in(cast$y, cast$x))
}

duckplyr_setequal <- function(.data, ...) {
  if (is_grouped_df(.data)) {
    testthat::skip("`setequal()` not supported for grouped_df")
  }

  if (inherits(.data, "rowwise_df")) {
    testthat::skip("`setequal()` not supported for rowwise_df")
  }

  .data <- as_duckplyr_df(.data)
  out <- setequal(.data, ...)
  out
}
