# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr slice_tail
#' @export
slice_tail.duckplyr_df <- function(.data, ..., n, prop, by = NULL) {
  # Our implementation
  force(.data)
  out <- NextMethod()
  out <- dplyr_reconstruct(out, .data)
  return(out)
}
