# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr tbl_vars
#' @export
tbl_vars.duckplyr_df <- function(x) {
  # Our implementation
  rel_try(
    {
      rel <- duckdb:::rel_from_altrep_df(x)
      return(rel_names(rel))
    }
  )

  # dplyr implementation
  names(x)
}

duckplyr_tbl_vars <- function(x, ...) {
  try_fetch(
    x <- as_duckplyr_df(x),
    error = function(e) {
      testthat::skip(conditionMessage(e))
    }
  )
  out <- tbl_vars(x, ...)
  out
}
