# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr tbl_vars
#' @export
tbl_vars.duckplyr_df <- function(x) {
  # Our implementation
  force(x)
  out <- NextMethod()
  return(out)

  # dplyr implementation
  names(x)
}

duckplyr_tbl_vars <- function(.data, ...) {
  .data <- as_duckplyr_df(.data)
  out <- tbl_vars(.data, ...)
  out
}
