# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr tbl_vars
#' @export
tbl_vars.duckplyr_df <- function(x) {
  # Our implementation
  force(x)
  out <- NextMethod()
  return(out)

  # dplyr implementation
  names(x)
}

duckplyr_tbl_vars <- function(x, ...) {
  if (!identical(class(x), "data.frame") && !identical(class(x), c("tbl_df", "tbl", "data.frame"))) {
    testthat::skip("`tbl_vars()` only supported for plain data frames or tibbles")
  }

  x <- as_duckplyr_df(x)
  out <- tbl_vars(x, ...)
  out
}
