# Generated by meta_replay_to_fun_file(), do not edit by hand
tpch_raw_02 <- function(con, experimental) {
  df1 <- partsupp
  rel1 <- duckdb:::rel_from_df(con, df1, experimental = experimental)
  rel2 <- duckdb:::rel_project(
    rel1,
    list(
      {
        tmp_expr <- duckdb:::expr_reference("ps_partkey")
        duckdb:::expr_set_alias(tmp_expr, "ps_partkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("ps_suppkey")
        duckdb:::expr_set_alias(tmp_expr, "ps_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("ps_supplycost")
        duckdb:::expr_set_alias(tmp_expr, "ps_supplycost")
        tmp_expr
      }
    )
  )
  df2 <- part
  rel3 <- duckdb:::rel_from_df(con, df2, experimental = experimental)
  rel4 <- duckdb:::rel_project(
    rel3,
    list(
      {
        tmp_expr <- duckdb:::expr_reference("p_partkey")
        duckdb:::expr_set_alias(tmp_expr, "p_partkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_type")
        duckdb:::expr_set_alias(tmp_expr, "p_type")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_size")
        duckdb:::expr_set_alias(tmp_expr, "p_size")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_mfgr")
        duckdb:::expr_set_alias(tmp_expr, "p_mfgr")
        tmp_expr
      }
    )
  )
  rel5 <- duckdb:::rel_filter(
    rel4,
    list(
      duckdb:::expr_function(
        "==",
        list(
          duckdb:::expr_reference("p_size"),
          if ("experimental" %in% names(formals(duckdb:::expr_constant))) {
            duckdb:::expr_constant(15, experimental = experimental)
          } else {
            duckdb:::expr_constant(15)
          }
        )
      ),
      duckdb:::expr_function(
        "grepl",
        list(
          if ("experimental" %in% names(formals(duckdb:::expr_constant))) {
            duckdb:::expr_constant("BRASS$", experimental = experimental)
          } else {
            duckdb:::expr_constant("BRASS$")
          },
          duckdb:::expr_reference("p_type")
        )
      )
    )
  )
  rel6 <- duckdb:::rel_project(
    rel5,
    list(
      {
        tmp_expr <- duckdb:::expr_reference("p_partkey")
        duckdb:::expr_set_alias(tmp_expr, "p_partkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_mfgr")
        duckdb:::expr_set_alias(tmp_expr, "p_mfgr")
        tmp_expr
      }
    )
  )
  rel7 <- duckdb:::rel_set_alias(rel6, "lhs")
  rel8 <- duckdb:::rel_set_alias(rel2, "rhs")
  rel9 <- duckdb:::rel_join(
    rel7,
    rel8,
    list(
      duckdb:::expr_function(
        "==",
        list(duckdb:::expr_reference("p_partkey", rel7), duckdb:::expr_reference("ps_partkey", rel8))
      )
    ),
    "inner"
  )
  rel10 <- duckdb:::rel_project(
    rel9,
    list(
      {
        tmp_expr <- duckdb:::expr_function(
          "___coalesce",
          list(duckdb:::expr_reference("p_partkey", rel7), duckdb:::expr_reference("ps_partkey", rel8))
        )
        duckdb:::expr_set_alias(tmp_expr, "p_partkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_mfgr")
        duckdb:::expr_set_alias(tmp_expr, "p_mfgr")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("ps_suppkey")
        duckdb:::expr_set_alias(tmp_expr, "ps_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("ps_supplycost")
        duckdb:::expr_set_alias(tmp_expr, "ps_supplycost")
        tmp_expr
      }
    )
  )
  df3 <- supplier
  rel11 <- duckdb:::rel_from_df(con, df3, experimental = experimental)
  rel12 <- duckdb:::rel_project(
    rel11,
    list(
      {
        tmp_expr <- duckdb:::expr_reference("s_suppkey")
        duckdb:::expr_set_alias(tmp_expr, "s_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_nationkey")
        duckdb:::expr_set_alias(tmp_expr, "s_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_acctbal")
        duckdb:::expr_set_alias(tmp_expr, "s_acctbal")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_name")
        duckdb:::expr_set_alias(tmp_expr, "s_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_address")
        duckdb:::expr_set_alias(tmp_expr, "s_address")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_phone")
        duckdb:::expr_set_alias(tmp_expr, "s_phone")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_comment")
        duckdb:::expr_set_alias(tmp_expr, "s_comment")
        tmp_expr
      }
    )
  )
  rel13 <- duckdb:::rel_set_alias(rel10, "lhs")
  rel14 <- duckdb:::rel_set_alias(rel12, "rhs")
  rel15 <- duckdb:::rel_join(
    rel13,
    rel14,
    list(
      duckdb:::expr_function(
        "___eq_na_matches_na",
        list(duckdb:::expr_reference("ps_suppkey", rel13), duckdb:::expr_reference("s_suppkey", rel14))
      )
    ),
    "inner"
  )
  rel16 <- duckdb:::rel_project(
    rel15,
    list(
      {
        tmp_expr <- duckdb:::expr_reference("p_partkey")
        duckdb:::expr_set_alias(tmp_expr, "p_partkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_mfgr")
        duckdb:::expr_set_alias(tmp_expr, "p_mfgr")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_function(
          "___coalesce",
          list(duckdb:::expr_reference("ps_suppkey", rel13), duckdb:::expr_reference("s_suppkey", rel14))
        )
        duckdb:::expr_set_alias(tmp_expr, "ps_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("ps_supplycost")
        duckdb:::expr_set_alias(tmp_expr, "ps_supplycost")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_nationkey")
        duckdb:::expr_set_alias(tmp_expr, "s_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_acctbal")
        duckdb:::expr_set_alias(tmp_expr, "s_acctbal")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_name")
        duckdb:::expr_set_alias(tmp_expr, "s_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_address")
        duckdb:::expr_set_alias(tmp_expr, "s_address")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_phone")
        duckdb:::expr_set_alias(tmp_expr, "s_phone")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_comment")
        duckdb:::expr_set_alias(tmp_expr, "s_comment")
        tmp_expr
      }
    )
  )
  rel17 <- duckdb:::rel_project(
    rel16,
    list(
      {
        tmp_expr <- duckdb:::expr_reference("p_partkey")
        duckdb:::expr_set_alias(tmp_expr, "p_partkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("ps_supplycost")
        duckdb:::expr_set_alias(tmp_expr, "ps_supplycost")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_mfgr")
        duckdb:::expr_set_alias(tmp_expr, "p_mfgr")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_nationkey")
        duckdb:::expr_set_alias(tmp_expr, "s_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_acctbal")
        duckdb:::expr_set_alias(tmp_expr, "s_acctbal")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_name")
        duckdb:::expr_set_alias(tmp_expr, "s_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_address")
        duckdb:::expr_set_alias(tmp_expr, "s_address")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_phone")
        duckdb:::expr_set_alias(tmp_expr, "s_phone")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_comment")
        duckdb:::expr_set_alias(tmp_expr, "s_comment")
        tmp_expr
      }
    )
  )
  df4 <- region
  rel18 <- duckdb:::rel_from_df(con, df4, experimental = experimental)
  rel19 <- duckdb:::rel_filter(
    rel18,
    list(
      duckdb:::expr_function(
        "==",
        list(
          duckdb:::expr_reference("r_name"),
          if ("experimental" %in% names(formals(duckdb:::expr_constant))) {
            duckdb:::expr_constant("EUROPE", experimental = experimental)
          } else {
            duckdb:::expr_constant("EUROPE")
          }
        )
      )
    )
  )
  df5 <- nation
  rel20 <- duckdb:::rel_from_df(con, df5, experimental = experimental)
  rel21 <- duckdb:::rel_set_alias(rel20, "lhs")
  rel22 <- duckdb:::rel_set_alias(rel19, "rhs")
  rel23 <- duckdb:::rel_join(
    rel21,
    rel22,
    list(
      duckdb:::expr_function(
        "___eq_na_matches_na",
        list(duckdb:::expr_reference("n_regionkey", rel21), duckdb:::expr_reference("r_regionkey", rel22))
      )
    ),
    "inner"
  )
  rel24 <- duckdb:::rel_project(
    rel23,
    list(
      {
        tmp_expr <- duckdb:::expr_reference("n_nationkey")
        duckdb:::expr_set_alias(tmp_expr, "n_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("n_name")
        duckdb:::expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_function(
          "___coalesce",
          list(duckdb:::expr_reference("n_regionkey", rel21), duckdb:::expr_reference("r_regionkey", rel22))
        )
        duckdb:::expr_set_alias(tmp_expr, "n_regionkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("n_comment")
        duckdb:::expr_set_alias(tmp_expr, "n_comment")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("r_name")
        duckdb:::expr_set_alias(tmp_expr, "r_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("r_comment")
        duckdb:::expr_set_alias(tmp_expr, "r_comment")
        tmp_expr
      }
    )
  )
  rel25 <- duckdb:::rel_project(
    rel24,
    list(
      {
        tmp_expr <- duckdb:::expr_reference("n_nationkey")
        duckdb:::expr_set_alias(tmp_expr, "n_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("n_name")
        duckdb:::expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      }
    )
  )
  rel26 <- duckdb:::rel_set_alias(rel17, "lhs")
  rel27 <- duckdb:::rel_set_alias(rel25, "rhs")
  rel28 <- duckdb:::rel_join(
    rel26,
    rel27,
    list(
      duckdb:::expr_function(
        "___eq_na_matches_na",
        list(duckdb:::expr_reference("s_nationkey", rel26), duckdb:::expr_reference("n_nationkey", rel27))
      )
    ),
    "inner"
  )
  rel29 <- duckdb:::rel_project(
    rel28,
    list(
      {
        tmp_expr <- duckdb:::expr_reference("p_partkey")
        duckdb:::expr_set_alias(tmp_expr, "p_partkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("ps_supplycost")
        duckdb:::expr_set_alias(tmp_expr, "ps_supplycost")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_mfgr")
        duckdb:::expr_set_alias(tmp_expr, "p_mfgr")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_function(
          "___coalesce",
          list(duckdb:::expr_reference("s_nationkey", rel26), duckdb:::expr_reference("n_nationkey", rel27))
        )
        duckdb:::expr_set_alias(tmp_expr, "s_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_acctbal")
        duckdb:::expr_set_alias(tmp_expr, "s_acctbal")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_name")
        duckdb:::expr_set_alias(tmp_expr, "s_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_address")
        duckdb:::expr_set_alias(tmp_expr, "s_address")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_phone")
        duckdb:::expr_set_alias(tmp_expr, "s_phone")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_comment")
        duckdb:::expr_set_alias(tmp_expr, "s_comment")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("n_name")
        duckdb:::expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      }
    )
  )
  rel30 <- duckdb:::rel_project(
    rel29,
    list(
      {
        tmp_expr <- duckdb:::expr_reference("p_partkey")
        duckdb:::expr_set_alias(tmp_expr, "p_partkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("ps_supplycost")
        duckdb:::expr_set_alias(tmp_expr, "ps_supplycost")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_mfgr")
        duckdb:::expr_set_alias(tmp_expr, "p_mfgr")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("n_name")
        duckdb:::expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_acctbal")
        duckdb:::expr_set_alias(tmp_expr, "s_acctbal")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_name")
        duckdb:::expr_set_alias(tmp_expr, "s_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_address")
        duckdb:::expr_set_alias(tmp_expr, "s_address")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_phone")
        duckdb:::expr_set_alias(tmp_expr, "s_phone")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_comment")
        duckdb:::expr_set_alias(tmp_expr, "s_comment")
        tmp_expr
      }
    )
  )
  rel31 <- duckdb:::rel_aggregate(
    rel30,
    groups = list(duckdb:::expr_reference("p_partkey")),
    aggregates = list({
      tmp_expr <- duckdb:::expr_function("min", list(duckdb:::expr_reference("ps_supplycost")))
      duckdb:::expr_set_alias(tmp_expr, "min_ps_supplycost")
      tmp_expr
    })
  )
  rel32 <- duckdb:::rel_set_alias(rel30, "lhs")
  rel33 <- duckdb:::rel_set_alias(rel31, "rhs")
  rel34 <- duckdb:::rel_project(
    rel32,
    list(
      {
        tmp_expr <- duckdb:::expr_reference("p_partkey")
        duckdb:::expr_set_alias(tmp_expr, "p_partkey_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("ps_supplycost")
        duckdb:::expr_set_alias(tmp_expr, "ps_supplycost_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_mfgr")
        duckdb:::expr_set_alias(tmp_expr, "p_mfgr_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("n_name")
        duckdb:::expr_set_alias(tmp_expr, "n_name_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_acctbal")
        duckdb:::expr_set_alias(tmp_expr, "s_acctbal_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_name")
        duckdb:::expr_set_alias(tmp_expr, "s_name_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_address")
        duckdb:::expr_set_alias(tmp_expr, "s_address_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_phone")
        duckdb:::expr_set_alias(tmp_expr, "s_phone_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_comment")
        duckdb:::expr_set_alias(tmp_expr, "s_comment_x")
        tmp_expr
      }
    )
  )
  rel35 <- duckdb:::rel_project(
    rel33,
    list(
      {
        tmp_expr <- duckdb:::expr_reference("p_partkey")
        duckdb:::expr_set_alias(tmp_expr, "p_partkey_y")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("min_ps_supplycost")
        duckdb:::expr_set_alias(tmp_expr, "min_ps_supplycost_y")
        tmp_expr
      }
    )
  )
  rel36 <- duckdb:::rel_join(
    rel34,
    rel35,
    list(
      duckdb:::expr_function(
        "___eq_na_matches_na",
        list(duckdb:::expr_reference("p_partkey_x", rel34), duckdb:::expr_reference("p_partkey_y", rel35))
      ),
      duckdb:::expr_function(
        "___eq_na_matches_na",
        list(duckdb:::expr_reference("ps_supplycost_x", rel34), duckdb:::expr_reference("min_ps_supplycost_y", rel35))
      )
    ),
    "inner"
  )
  rel37 <- duckdb:::rel_project(
    rel36,
    list(
      {
        tmp_expr <- duckdb:::expr_function(
          "___coalesce",
          list(duckdb:::expr_reference("p_partkey_x", rel34), duckdb:::expr_reference("p_partkey_y", rel35))
        )
        duckdb:::expr_set_alias(tmp_expr, "p_partkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_function(
          "___coalesce",
          list(duckdb:::expr_reference("ps_supplycost_x", rel34), duckdb:::expr_reference("min_ps_supplycost_y", rel35))
        )
        duckdb:::expr_set_alias(tmp_expr, "ps_supplycost")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_mfgr_x")
        duckdb:::expr_set_alias(tmp_expr, "p_mfgr")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("n_name_x")
        duckdb:::expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_acctbal_x")
        duckdb:::expr_set_alias(tmp_expr, "s_acctbal")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_name_x")
        duckdb:::expr_set_alias(tmp_expr, "s_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_address_x")
        duckdb:::expr_set_alias(tmp_expr, "s_address")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_phone_x")
        duckdb:::expr_set_alias(tmp_expr, "s_phone")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_comment_x")
        duckdb:::expr_set_alias(tmp_expr, "s_comment")
        tmp_expr
      }
    )
  )
  rel38 <- duckdb:::rel_project(
    rel37,
    list(
      {
        tmp_expr <- duckdb:::expr_reference("s_acctbal")
        duckdb:::expr_set_alias(tmp_expr, "s_acctbal")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_name")
        duckdb:::expr_set_alias(tmp_expr, "s_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("n_name")
        duckdb:::expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_partkey")
        duckdb:::expr_set_alias(tmp_expr, "p_partkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_mfgr")
        duckdb:::expr_set_alias(tmp_expr, "p_mfgr")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_address")
        duckdb:::expr_set_alias(tmp_expr, "s_address")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_phone")
        duckdb:::expr_set_alias(tmp_expr, "s_phone")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("s_comment")
        duckdb:::expr_set_alias(tmp_expr, "s_comment")
        tmp_expr
      }
    )
  )
  rel39 <- duckdb:::rel_order(
    rel38,
    list(duckdb:::expr_function("desc", list(duckdb:::expr_reference("s_acctbal"))), duckdb:::expr_reference("n_name"), duckdb:::expr_reference("s_name"), duckdb:::expr_reference("p_partkey"))
  )
  rel40 <- duckdb:::rel_limit(rel39, 100)
  rel40
  duckdb:::rel_to_altrep(rel40)
}
