# Generated by meta_replay_to_fun_file(), do not edit by hand
tpch_raw_14 <- function(con, experimental) {
  df1 <- lineitem
  rel1 <- duckdb:::rel_from_df(con, df1, experimental = experimental)
  rel2 <- duckdb:::rel_filter(
    rel1,
    list(
      duckdb:::expr_function(
        ">=",
        list(
          duckdb:::expr_reference("l_shipdate"),
          duckdb:::expr_function(
            "as.Date",
            list(
              if ("experimental" %in% names(formals(duckdb:::expr_constant))) {
                duckdb:::expr_constant("1995-09-01", experimental = experimental)
              } else {
                duckdb:::expr_constant("1995-09-01")
              }
            )
          )
        )
      ),
      duckdb:::expr_function(
        "<",
        list(
          duckdb:::expr_reference("l_shipdate"),
          duckdb:::expr_function(
            "as.Date",
            list(
              if ("experimental" %in% names(formals(duckdb:::expr_constant))) {
                duckdb:::expr_constant("1995-10-01", experimental = experimental)
              } else {
                duckdb:::expr_constant("1995-10-01")
              }
            )
          )
        )
      )
    )
  )
  rel3 <- duckdb:::rel_set_alias(rel2, "lhs")
  df2 <- part
  rel4 <- duckdb:::rel_from_df(con, df2, experimental = experimental)
  rel5 <- duckdb:::rel_set_alias(rel4, "rhs")
  rel6 <- duckdb:::rel_join(
    rel3,
    rel5,
    list(
      duckdb:::expr_function(
        "==",
        list(duckdb:::expr_reference("l_partkey", rel3), duckdb:::expr_reference("p_partkey", rel5))
      )
    ),
    "inner"
  )
  rel7 <- duckdb:::rel_project(
    rel6,
    list(
      {
        tmp_expr <- duckdb:::expr_reference("l_orderkey")
        duckdb:::expr_set_alias(tmp_expr, "l_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_function(
          "___coalesce",
          list(duckdb:::expr_reference("l_partkey", rel3), duckdb:::expr_reference("p_partkey", rel5))
        )
        duckdb:::expr_set_alias(tmp_expr, "l_partkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_suppkey")
        duckdb:::expr_set_alias(tmp_expr, "l_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_linenumber")
        duckdb:::expr_set_alias(tmp_expr, "l_linenumber")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_quantity")
        duckdb:::expr_set_alias(tmp_expr, "l_quantity")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_extendedprice")
        duckdb:::expr_set_alias(tmp_expr, "l_extendedprice")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_discount")
        duckdb:::expr_set_alias(tmp_expr, "l_discount")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_tax")
        duckdb:::expr_set_alias(tmp_expr, "l_tax")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_returnflag")
        duckdb:::expr_set_alias(tmp_expr, "l_returnflag")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_linestatus")
        duckdb:::expr_set_alias(tmp_expr, "l_linestatus")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_shipdate")
        duckdb:::expr_set_alias(tmp_expr, "l_shipdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_commitdate")
        duckdb:::expr_set_alias(tmp_expr, "l_commitdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_receiptdate")
        duckdb:::expr_set_alias(tmp_expr, "l_receiptdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_shipinstruct")
        duckdb:::expr_set_alias(tmp_expr, "l_shipinstruct")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_shipmode")
        duckdb:::expr_set_alias(tmp_expr, "l_shipmode")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_comment")
        duckdb:::expr_set_alias(tmp_expr, "l_comment")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_name")
        duckdb:::expr_set_alias(tmp_expr, "p_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_mfgr")
        duckdb:::expr_set_alias(tmp_expr, "p_mfgr")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_brand")
        duckdb:::expr_set_alias(tmp_expr, "p_brand")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_type")
        duckdb:::expr_set_alias(tmp_expr, "p_type")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_size")
        duckdb:::expr_set_alias(tmp_expr, "p_size")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_container")
        duckdb:::expr_set_alias(tmp_expr, "p_container")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_retailprice")
        duckdb:::expr_set_alias(tmp_expr, "p_retailprice")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_comment")
        duckdb:::expr_set_alias(tmp_expr, "p_comment")
        tmp_expr
      }
    )
  )
  rel8 <- duckdb:::rel_aggregate(
    rel7,
    groups = list(),
    aggregates = list({
      tmp_expr <- duckdb:::expr_function(
        "/",
        list(
          duckdb:::expr_function(
            "*",
            list(
              if ("experimental" %in% names(formals(duckdb:::expr_constant))) {
                duckdb:::expr_constant(100, experimental = experimental)
              } else {
                duckdb:::expr_constant(100)
              },
              duckdb:::expr_function(
                "sum",
                list(
                  duckdb:::expr_function(
                    "ifelse",
                    list(
                      duckdb:::expr_function(
                        "grepl",
                        list(
                          if ("experimental" %in% names(formals(duckdb:::expr_constant))) {
                            duckdb:::expr_constant("^PROMO", experimental = experimental)
                          } else {
                            duckdb:::expr_constant("^PROMO")
                          },
                          duckdb:::expr_reference("p_type")
                        )
                      ),
                      duckdb:::expr_function(
                        "*",
                        list(
                          duckdb:::expr_reference("l_extendedprice"),
                          duckdb:::expr_function(
                            "-",
                            list(
                              if ("experimental" %in% names(formals(duckdb:::expr_constant))) {
                                duckdb:::expr_constant(1, experimental = experimental)
                              } else {
                                duckdb:::expr_constant(1)
                              },
                              duckdb:::expr_reference("l_discount")
                            )
                          )
                        )
                      ),
                      if ("experimental" %in% names(formals(duckdb:::expr_constant))) {
                        duckdb:::expr_constant(0, experimental = experimental)
                      } else {
                        duckdb:::expr_constant(0)
                      }
                    )
                  )
                )
              )
            )
          ),
          duckdb:::expr_function(
            "sum",
            list(
              duckdb:::expr_function(
                "*",
                list(
                  duckdb:::expr_reference("l_extendedprice"),
                  duckdb:::expr_function(
                    "-",
                    list(
                      if ("experimental" %in% names(formals(duckdb:::expr_constant))) {
                        duckdb:::expr_constant(1, experimental = experimental)
                      } else {
                        duckdb:::expr_constant(1)
                      },
                      duckdb:::expr_reference("l_discount")
                    )
                  )
                )
              )
            )
          )
        )
      )
      duckdb:::expr_set_alias(tmp_expr, "promo_revenue")
      tmp_expr
    })
  )
  rel9 <- duckdb:::rel_distinct(rel8)
  rel9
  duckdb:::rel_to_altrep(rel9)
}
