# Generated by meta_replay_to_fun_file(), do not edit by hand
tpch_raw_17 <- function(con, experimental) {
  df1 <- part
  rel1 <- duckdb:::rel_from_df(con, df1, experimental = experimental)
  rel2 <- duckdb:::rel_filter(
    rel1,
    list(
      duckdb:::expr_function(
        "==",
        list(
          duckdb:::expr_reference("p_brand"),
          if ("experimental" %in% names(formals(duckdb:::expr_constant))) {
            duckdb:::expr_constant("Brand#23", experimental = experimental)
          } else {
            duckdb:::expr_constant("Brand#23")
          }
        )
      ),
      duckdb:::expr_function(
        "==",
        list(
          duckdb:::expr_reference("p_container"),
          if ("experimental" %in% names(formals(duckdb:::expr_constant))) {
            duckdb:::expr_constant("MED BOX", experimental = experimental)
          } else {
            duckdb:::expr_constant("MED BOX")
          }
        )
      )
    )
  )
  df2 <- lineitem
  rel3 <- duckdb:::rel_from_df(con, df2, experimental = experimental)
  rel4 <- duckdb:::rel_set_alias(rel3, "lhs")
  rel5 <- duckdb:::rel_set_alias(rel2, "rhs")
  rel6 <- duckdb:::rel_join(
    rel4,
    rel5,
    list(
      duckdb:::expr_function(
        "==",
        list(duckdb:::expr_reference("l_partkey", rel4), duckdb:::expr_reference("p_partkey", rel5))
      )
    ),
    "inner"
  )
  rel7 <- duckdb:::rel_project(
    rel6,
    list(
      {
        tmp_expr <- duckdb:::expr_reference("l_orderkey")
        duckdb:::expr_set_alias(tmp_expr, "l_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_function(
          "___coalesce",
          list(duckdb:::expr_reference("l_partkey", rel4), duckdb:::expr_reference("p_partkey", rel5))
        )
        duckdb:::expr_set_alias(tmp_expr, "l_partkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_suppkey")
        duckdb:::expr_set_alias(tmp_expr, "l_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_linenumber")
        duckdb:::expr_set_alias(tmp_expr, "l_linenumber")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_quantity")
        duckdb:::expr_set_alias(tmp_expr, "l_quantity")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_extendedprice")
        duckdb:::expr_set_alias(tmp_expr, "l_extendedprice")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_discount")
        duckdb:::expr_set_alias(tmp_expr, "l_discount")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_tax")
        duckdb:::expr_set_alias(tmp_expr, "l_tax")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_returnflag")
        duckdb:::expr_set_alias(tmp_expr, "l_returnflag")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_linestatus")
        duckdb:::expr_set_alias(tmp_expr, "l_linestatus")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_shipdate")
        duckdb:::expr_set_alias(tmp_expr, "l_shipdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_commitdate")
        duckdb:::expr_set_alias(tmp_expr, "l_commitdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_receiptdate")
        duckdb:::expr_set_alias(tmp_expr, "l_receiptdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_shipinstruct")
        duckdb:::expr_set_alias(tmp_expr, "l_shipinstruct")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_shipmode")
        duckdb:::expr_set_alias(tmp_expr, "l_shipmode")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_comment")
        duckdb:::expr_set_alias(tmp_expr, "l_comment")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_name")
        duckdb:::expr_set_alias(tmp_expr, "p_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_mfgr")
        duckdb:::expr_set_alias(tmp_expr, "p_mfgr")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_brand")
        duckdb:::expr_set_alias(tmp_expr, "p_brand")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_type")
        duckdb:::expr_set_alias(tmp_expr, "p_type")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_size")
        duckdb:::expr_set_alias(tmp_expr, "p_size")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_container")
        duckdb:::expr_set_alias(tmp_expr, "p_container")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_retailprice")
        duckdb:::expr_set_alias(tmp_expr, "p_retailprice")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_comment")
        duckdb:::expr_set_alias(tmp_expr, "p_comment")
        tmp_expr
      }
    )
  )
  rel8 <- duckdb:::rel_aggregate(
    rel7,
    groups = list(duckdb:::expr_reference("l_partkey")),
    aggregates = list({
      tmp_expr <- duckdb:::expr_function(
        "*",
        list(
          if ("experimental" %in% names(formals(duckdb:::expr_constant))) {
            duckdb:::expr_constant(0.2, experimental = experimental)
          } else {
            duckdb:::expr_constant(0.2)
          },
          duckdb:::expr_function("mean", list(duckdb:::expr_reference("l_quantity")))
        )
      )
      duckdb:::expr_set_alias(tmp_expr, "quantity_threshold")
      tmp_expr
    })
  )
  rel9 <- duckdb:::rel_set_alias(rel7, "lhs")
  rel10 <- duckdb:::rel_set_alias(rel8, "rhs")
  rel11 <- duckdb:::rel_project(
    rel9,
    list(
      {
        tmp_expr <- duckdb:::expr_reference("l_orderkey")
        duckdb:::expr_set_alias(tmp_expr, "l_orderkey_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_partkey")
        duckdb:::expr_set_alias(tmp_expr, "l_partkey_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_suppkey")
        duckdb:::expr_set_alias(tmp_expr, "l_suppkey_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_linenumber")
        duckdb:::expr_set_alias(tmp_expr, "l_linenumber_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_quantity")
        duckdb:::expr_set_alias(tmp_expr, "l_quantity_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_extendedprice")
        duckdb:::expr_set_alias(tmp_expr, "l_extendedprice_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_discount")
        duckdb:::expr_set_alias(tmp_expr, "l_discount_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_tax")
        duckdb:::expr_set_alias(tmp_expr, "l_tax_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_returnflag")
        duckdb:::expr_set_alias(tmp_expr, "l_returnflag_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_linestatus")
        duckdb:::expr_set_alias(tmp_expr, "l_linestatus_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_shipdate")
        duckdb:::expr_set_alias(tmp_expr, "l_shipdate_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_commitdate")
        duckdb:::expr_set_alias(tmp_expr, "l_commitdate_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_receiptdate")
        duckdb:::expr_set_alias(tmp_expr, "l_receiptdate_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_shipinstruct")
        duckdb:::expr_set_alias(tmp_expr, "l_shipinstruct_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_shipmode")
        duckdb:::expr_set_alias(tmp_expr, "l_shipmode_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_comment")
        duckdb:::expr_set_alias(tmp_expr, "l_comment_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_name")
        duckdb:::expr_set_alias(tmp_expr, "p_name_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_mfgr")
        duckdb:::expr_set_alias(tmp_expr, "p_mfgr_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_brand")
        duckdb:::expr_set_alias(tmp_expr, "p_brand_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_type")
        duckdb:::expr_set_alias(tmp_expr, "p_type_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_size")
        duckdb:::expr_set_alias(tmp_expr, "p_size_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_container")
        duckdb:::expr_set_alias(tmp_expr, "p_container_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_retailprice")
        duckdb:::expr_set_alias(tmp_expr, "p_retailprice_x")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_comment")
        duckdb:::expr_set_alias(tmp_expr, "p_comment_x")
        tmp_expr
      }
    )
  )
  rel12 <- duckdb:::rel_project(
    rel10,
    list(
      {
        tmp_expr <- duckdb:::expr_reference("l_partkey")
        duckdb:::expr_set_alias(tmp_expr, "l_partkey_y")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("quantity_threshold")
        duckdb:::expr_set_alias(tmp_expr, "quantity_threshold_y")
        tmp_expr
      }
    )
  )
  rel13 <- duckdb:::rel_join(
    rel11,
    rel12,
    list(
      duckdb:::expr_function(
        "==",
        list(duckdb:::expr_reference("l_partkey_x", rel11), duckdb:::expr_reference("l_partkey_y", rel12))
      )
    ),
    "inner"
  )
  rel14 <- duckdb:::rel_project(
    rel13,
    list(
      {
        tmp_expr <- duckdb:::expr_reference("l_orderkey_x")
        duckdb:::expr_set_alias(tmp_expr, "l_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_function(
          "___coalesce",
          list(duckdb:::expr_reference("l_partkey_x", rel11), duckdb:::expr_reference("l_partkey_y", rel12))
        )
        duckdb:::expr_set_alias(tmp_expr, "l_partkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_suppkey_x")
        duckdb:::expr_set_alias(tmp_expr, "l_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_linenumber_x")
        duckdb:::expr_set_alias(tmp_expr, "l_linenumber")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_quantity_x")
        duckdb:::expr_set_alias(tmp_expr, "l_quantity")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_extendedprice_x")
        duckdb:::expr_set_alias(tmp_expr, "l_extendedprice")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_discount_x")
        duckdb:::expr_set_alias(tmp_expr, "l_discount")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_tax_x")
        duckdb:::expr_set_alias(tmp_expr, "l_tax")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_returnflag_x")
        duckdb:::expr_set_alias(tmp_expr, "l_returnflag")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_linestatus_x")
        duckdb:::expr_set_alias(tmp_expr, "l_linestatus")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_shipdate_x")
        duckdb:::expr_set_alias(tmp_expr, "l_shipdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_commitdate_x")
        duckdb:::expr_set_alias(tmp_expr, "l_commitdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_receiptdate_x")
        duckdb:::expr_set_alias(tmp_expr, "l_receiptdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_shipinstruct_x")
        duckdb:::expr_set_alias(tmp_expr, "l_shipinstruct")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_shipmode_x")
        duckdb:::expr_set_alias(tmp_expr, "l_shipmode")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("l_comment_x")
        duckdb:::expr_set_alias(tmp_expr, "l_comment")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_name_x")
        duckdb:::expr_set_alias(tmp_expr, "p_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_mfgr_x")
        duckdb:::expr_set_alias(tmp_expr, "p_mfgr")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_brand_x")
        duckdb:::expr_set_alias(tmp_expr, "p_brand")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_type_x")
        duckdb:::expr_set_alias(tmp_expr, "p_type")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_size_x")
        duckdb:::expr_set_alias(tmp_expr, "p_size")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_container_x")
        duckdb:::expr_set_alias(tmp_expr, "p_container")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_retailprice_x")
        duckdb:::expr_set_alias(tmp_expr, "p_retailprice")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("p_comment_x")
        duckdb:::expr_set_alias(tmp_expr, "p_comment")
        tmp_expr
      },
      {
        tmp_expr <- duckdb:::expr_reference("quantity_threshold_y")
        duckdb:::expr_set_alias(tmp_expr, "quantity_threshold")
        tmp_expr
      }
    )
  )
  rel15 <- duckdb:::rel_filter(
    rel14,
    list(
      duckdb:::expr_function(
        "<",
        list(duckdb:::expr_reference("l_quantity"), duckdb:::expr_reference("quantity_threshold"))
      )
    )
  )
  rel16 <- duckdb:::rel_aggregate(
    rel15,
    groups = list(),
    aggregates = list({
      tmp_expr <- duckdb:::expr_function(
        "/",
        list(
          duckdb:::expr_function("sum", list(duckdb:::expr_reference("l_extendedprice"))),
          if ("experimental" %in% names(formals(duckdb:::expr_constant))) {
            duckdb:::expr_constant(7, experimental = experimental)
          } else {
            duckdb:::expr_constant(7)
          }
        )
      )
      duckdb:::expr_set_alias(tmp_expr, "avg_yearly")
      tmp_expr
    })
  )
  rel17 <- duckdb:::rel_distinct(rel16)
  rel17
  duckdb:::rel_to_altrep(rel17)
}
