# Generated by meta_replay_to_fun_file(), do not edit by hand
tpch_raw_oo_05 <- function(con, experimental) {
  df1 <- nation
  rel1 <- duckdb$rel_from_df(con, df1, experimental = experimental)
  rel2 <- duckdb$rel_project(
    rel1,
    list(
      {
        tmp_expr <- duckdb$expr_reference("n_nationkey")
        duckdb$expr_set_alias(tmp_expr, "n_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_regionkey")
        duckdb$expr_set_alias(tmp_expr, "n_regionkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_name")
        duckdb$expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      }
    )
  )
  df2 <- region
  rel3 <- duckdb$rel_from_df(con, df2, experimental = experimental)
  rel4 <- duckdb$rel_project(
    rel3,
    list(
      {
        tmp_expr <- duckdb$expr_reference("r_regionkey")
        duckdb$expr_set_alias(tmp_expr, "r_regionkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("r_name")
        duckdb$expr_set_alias(tmp_expr, "r_name")
        tmp_expr
      }
    )
  )
  rel5 <- duckdb$rel_project(
    rel4,
    list(
      {
        tmp_expr <- duckdb$expr_reference("r_regionkey")
        duckdb$expr_set_alias(tmp_expr, "r_regionkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("r_name")
        duckdb$expr_set_alias(tmp_expr, "r_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_window(duckdb$expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        duckdb$expr_set_alias(tmp_expr, "___row_number")
        tmp_expr
      }
    )
  )
  rel6 <- duckdb$rel_filter(
    rel5,
    list(
      duckdb$expr_function(
        "==",
        list(
          duckdb$expr_reference("r_name"),
          if ("experimental" %in% names(formals(duckdb$expr_constant))) {
            duckdb$expr_constant("ASIA", experimental = experimental)
          } else {
            duckdb$expr_constant("ASIA")
          }
        )
      )
    )
  )
  rel7 <- duckdb$rel_order(rel6, list(duckdb$expr_reference("___row_number")))
  rel8 <- duckdb$rel_project(
    rel7,
    list(
      {
        tmp_expr <- duckdb$expr_reference("r_regionkey")
        duckdb$expr_set_alias(tmp_expr, "r_regionkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("r_name")
        duckdb$expr_set_alias(tmp_expr, "r_name")
        tmp_expr
      }
    )
  )
  rel9 <- duckdb$rel_set_alias(rel2, "lhs")
  rel10 <- duckdb$rel_set_alias(rel8, "rhs")
  rel11 <- duckdb$rel_project(
    rel9,
    list(
      {
        tmp_expr <- duckdb$expr_reference("n_nationkey")
        duckdb$expr_set_alias(tmp_expr, "n_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_regionkey")
        duckdb$expr_set_alias(tmp_expr, "n_regionkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_name")
        duckdb$expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_window(duckdb$expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        duckdb$expr_set_alias(tmp_expr, "___row_number_x")
        tmp_expr
      }
    )
  )
  rel12 <- duckdb$rel_project(
    rel10,
    list(
      {
        tmp_expr <- duckdb$expr_reference("r_regionkey")
        duckdb$expr_set_alias(tmp_expr, "r_regionkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("r_name")
        duckdb$expr_set_alias(tmp_expr, "r_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_window(duckdb$expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        duckdb$expr_set_alias(tmp_expr, "___row_number_y")
        tmp_expr
      }
    )
  )
  rel13 <- duckdb$rel_join(
    rel11,
    rel12,
    list(
      duckdb$expr_function(
        "==",
        list(duckdb$expr_reference("n_regionkey", rel11), duckdb$expr_reference("r_regionkey", rel12))
      )
    ),
    "inner"
  )
  rel14 <- duckdb$rel_order(
    rel13,
    list(duckdb$expr_reference("___row_number_x", rel11), duckdb$expr_reference("___row_number_y", rel12))
  )
  rel15 <- duckdb$rel_project(
    rel14,
    list(
      {
        tmp_expr <- duckdb$expr_reference("n_nationkey")
        duckdb$expr_set_alias(tmp_expr, "n_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_function(
          "___coalesce",
          list(duckdb$expr_reference("n_regionkey", rel11), duckdb$expr_reference("r_regionkey", rel12))
        )
        duckdb$expr_set_alias(tmp_expr, "n_regionkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_name")
        duckdb$expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("r_name")
        duckdb$expr_set_alias(tmp_expr, "r_name")
        tmp_expr
      }
    )
  )
  rel16 <- duckdb$rel_project(
    rel15,
    list(
      {
        tmp_expr <- duckdb$expr_reference("n_nationkey")
        duckdb$expr_set_alias(tmp_expr, "n_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_name")
        duckdb$expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      }
    )
  )
  df3 <- supplier
  rel17 <- duckdb$rel_from_df(con, df3, experimental = experimental)
  rel18 <- duckdb$rel_project(
    rel17,
    list(
      {
        tmp_expr <- duckdb$expr_reference("s_suppkey")
        duckdb$expr_set_alias(tmp_expr, "s_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("s_nationkey")
        duckdb$expr_set_alias(tmp_expr, "s_nationkey")
        tmp_expr
      }
    )
  )
  rel19 <- duckdb$rel_set_alias(rel18, "lhs")
  rel20 <- duckdb$rel_set_alias(rel16, "rhs")
  rel21 <- duckdb$rel_project(
    rel19,
    list(
      {
        tmp_expr <- duckdb$expr_reference("s_suppkey")
        duckdb$expr_set_alias(tmp_expr, "s_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("s_nationkey")
        duckdb$expr_set_alias(tmp_expr, "s_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_window(duckdb$expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        duckdb$expr_set_alias(tmp_expr, "___row_number_x")
        tmp_expr
      }
    )
  )
  rel22 <- duckdb$rel_project(
    rel20,
    list(
      {
        tmp_expr <- duckdb$expr_reference("n_nationkey")
        duckdb$expr_set_alias(tmp_expr, "n_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_name")
        duckdb$expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_window(duckdb$expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        duckdb$expr_set_alias(tmp_expr, "___row_number_y")
        tmp_expr
      }
    )
  )
  rel23 <- duckdb$rel_join(
    rel21,
    rel22,
    list(
      duckdb$expr_function(
        "==",
        list(duckdb$expr_reference("s_nationkey", rel21), duckdb$expr_reference("n_nationkey", rel22))
      )
    ),
    "inner"
  )
  rel24 <- duckdb$rel_order(
    rel23,
    list(duckdb$expr_reference("___row_number_x", rel21), duckdb$expr_reference("___row_number_y", rel22))
  )
  rel25 <- duckdb$rel_project(
    rel24,
    list(
      {
        tmp_expr <- duckdb$expr_reference("s_suppkey")
        duckdb$expr_set_alias(tmp_expr, "s_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_function(
          "___coalesce",
          list(duckdb$expr_reference("s_nationkey", rel21), duckdb$expr_reference("n_nationkey", rel22))
        )
        duckdb$expr_set_alias(tmp_expr, "s_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_name")
        duckdb$expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      }
    )
  )
  rel26 <- duckdb$rel_project(
    rel25,
    list(
      {
        tmp_expr <- duckdb$expr_reference("s_suppkey")
        duckdb$expr_set_alias(tmp_expr, "s_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("s_nationkey")
        duckdb$expr_set_alias(tmp_expr, "s_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_name")
        duckdb$expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      }
    )
  )
  df4 <- lineitem
  rel27 <- duckdb$rel_from_df(con, df4, experimental = experimental)
  rel28 <- duckdb$rel_project(
    rel27,
    list(
      {
        tmp_expr <- duckdb$expr_reference("l_suppkey")
        duckdb$expr_set_alias(tmp_expr, "l_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_orderkey")
        duckdb$expr_set_alias(tmp_expr, "l_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_extendedprice")
        duckdb$expr_set_alias(tmp_expr, "l_extendedprice")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_discount")
        duckdb$expr_set_alias(tmp_expr, "l_discount")
        tmp_expr
      }
    )
  )
  rel29 <- duckdb$rel_set_alias(rel28, "lhs")
  rel30 <- duckdb$rel_set_alias(rel26, "rhs")
  rel31 <- duckdb$rel_project(
    rel29,
    list(
      {
        tmp_expr <- duckdb$expr_reference("l_suppkey")
        duckdb$expr_set_alias(tmp_expr, "l_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_orderkey")
        duckdb$expr_set_alias(tmp_expr, "l_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_extendedprice")
        duckdb$expr_set_alias(tmp_expr, "l_extendedprice")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_discount")
        duckdb$expr_set_alias(tmp_expr, "l_discount")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_window(duckdb$expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        duckdb$expr_set_alias(tmp_expr, "___row_number_x")
        tmp_expr
      }
    )
  )
  rel32 <- duckdb$rel_project(
    rel30,
    list(
      {
        tmp_expr <- duckdb$expr_reference("s_suppkey")
        duckdb$expr_set_alias(tmp_expr, "s_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("s_nationkey")
        duckdb$expr_set_alias(tmp_expr, "s_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_name")
        duckdb$expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_window(duckdb$expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        duckdb$expr_set_alias(tmp_expr, "___row_number_y")
        tmp_expr
      }
    )
  )
  rel33 <- duckdb$rel_join(
    rel31,
    rel32,
    list(
      duckdb$expr_function(
        "==",
        list(duckdb$expr_reference("l_suppkey", rel31), duckdb$expr_reference("s_suppkey", rel32))
      )
    ),
    "inner"
  )
  rel34 <- duckdb$rel_order(
    rel33,
    list(duckdb$expr_reference("___row_number_x", rel31), duckdb$expr_reference("___row_number_y", rel32))
  )
  rel35 <- duckdb$rel_project(
    rel34,
    list(
      {
        tmp_expr <- duckdb$expr_function(
          "___coalesce",
          list(duckdb$expr_reference("l_suppkey", rel31), duckdb$expr_reference("s_suppkey", rel32))
        )
        duckdb$expr_set_alias(tmp_expr, "l_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_orderkey")
        duckdb$expr_set_alias(tmp_expr, "l_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_extendedprice")
        duckdb$expr_set_alias(tmp_expr, "l_extendedprice")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_discount")
        duckdb$expr_set_alias(tmp_expr, "l_discount")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("s_nationkey")
        duckdb$expr_set_alias(tmp_expr, "s_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_name")
        duckdb$expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      }
    )
  )
  df5 <- orders
  rel36 <- duckdb$rel_from_df(con, df5, experimental = experimental)
  rel37 <- duckdb$rel_project(
    rel36,
    list(
      {
        tmp_expr <- duckdb$expr_reference("o_orderdate")
        duckdb$expr_set_alias(tmp_expr, "o_orderdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("o_orderkey")
        duckdb$expr_set_alias(tmp_expr, "o_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("o_custkey")
        duckdb$expr_set_alias(tmp_expr, "o_custkey")
        tmp_expr
      }
    )
  )
  rel38 <- duckdb$rel_project(
    rel37,
    list(
      {
        tmp_expr <- duckdb$expr_reference("o_orderdate")
        duckdb$expr_set_alias(tmp_expr, "o_orderdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("o_orderkey")
        duckdb$expr_set_alias(tmp_expr, "o_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("o_custkey")
        duckdb$expr_set_alias(tmp_expr, "o_custkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_window(duckdb$expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        duckdb$expr_set_alias(tmp_expr, "___row_number")
        tmp_expr
      }
    )
  )
  rel39 <- duckdb$rel_filter(
    rel38,
    list(
      duckdb$expr_function(
        ">=",
        list(
          duckdb$expr_reference("o_orderdate"),
          if ("experimental" %in% names(formals(duckdb$expr_constant))) {
            duckdb$expr_constant(as.Date("1994-01-01"), experimental = experimental)
          } else {
            duckdb$expr_constant(as.Date("1994-01-01"))
          }
        )
      ),
      duckdb$expr_function(
        "<",
        list(
          duckdb$expr_reference("o_orderdate"),
          if ("experimental" %in% names(formals(duckdb$expr_constant))) {
            duckdb$expr_constant(as.Date("1995-01-01"), experimental = experimental)
          } else {
            duckdb$expr_constant(as.Date("1995-01-01"))
          }
        )
      )
    )
  )
  rel40 <- duckdb$rel_order(rel39, list(duckdb$expr_reference("___row_number")))
  rel41 <- duckdb$rel_project(
    rel40,
    list(
      {
        tmp_expr <- duckdb$expr_reference("o_orderdate")
        duckdb$expr_set_alias(tmp_expr, "o_orderdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("o_orderkey")
        duckdb$expr_set_alias(tmp_expr, "o_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("o_custkey")
        duckdb$expr_set_alias(tmp_expr, "o_custkey")
        tmp_expr
      }
    )
  )
  rel42 <- duckdb$rel_project(
    rel41,
    list(
      {
        tmp_expr <- duckdb$expr_reference("o_orderkey")
        duckdb$expr_set_alias(tmp_expr, "o_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("o_custkey")
        duckdb$expr_set_alias(tmp_expr, "o_custkey")
        tmp_expr
      }
    )
  )
  df6 <- customer
  rel43 <- duckdb$rel_from_df(con, df6, experimental = experimental)
  rel44 <- duckdb$rel_project(
    rel43,
    list(
      {
        tmp_expr <- duckdb$expr_reference("c_custkey")
        duckdb$expr_set_alias(tmp_expr, "c_custkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("c_nationkey")
        duckdb$expr_set_alias(tmp_expr, "c_nationkey")
        tmp_expr
      }
    )
  )
  rel45 <- duckdb$rel_set_alias(rel42, "lhs")
  rel46 <- duckdb$rel_set_alias(rel44, "rhs")
  rel47 <- duckdb$rel_project(
    rel45,
    list(
      {
        tmp_expr <- duckdb$expr_reference("o_orderkey")
        duckdb$expr_set_alias(tmp_expr, "o_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("o_custkey")
        duckdb$expr_set_alias(tmp_expr, "o_custkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_window(duckdb$expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        duckdb$expr_set_alias(tmp_expr, "___row_number_x")
        tmp_expr
      }
    )
  )
  rel48 <- duckdb$rel_project(
    rel46,
    list(
      {
        tmp_expr <- duckdb$expr_reference("c_custkey")
        duckdb$expr_set_alias(tmp_expr, "c_custkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("c_nationkey")
        duckdb$expr_set_alias(tmp_expr, "c_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_window(duckdb$expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        duckdb$expr_set_alias(tmp_expr, "___row_number_y")
        tmp_expr
      }
    )
  )
  rel49 <- duckdb$rel_join(
    rel47,
    rel48,
    list(
      duckdb$expr_function(
        "==",
        list(duckdb$expr_reference("o_custkey", rel47), duckdb$expr_reference("c_custkey", rel48))
      )
    ),
    "inner"
  )
  rel50 <- duckdb$rel_order(
    rel49,
    list(duckdb$expr_reference("___row_number_x", rel47), duckdb$expr_reference("___row_number_y", rel48))
  )
  rel51 <- duckdb$rel_project(
    rel50,
    list(
      {
        tmp_expr <- duckdb$expr_reference("o_orderkey")
        duckdb$expr_set_alias(tmp_expr, "o_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_function(
          "___coalesce",
          list(duckdb$expr_reference("o_custkey", rel47), duckdb$expr_reference("c_custkey", rel48))
        )
        duckdb$expr_set_alias(tmp_expr, "o_custkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("c_nationkey")
        duckdb$expr_set_alias(tmp_expr, "c_nationkey")
        tmp_expr
      }
    )
  )
  rel52 <- duckdb$rel_project(
    rel51,
    list(
      {
        tmp_expr <- duckdb$expr_reference("o_orderkey")
        duckdb$expr_set_alias(tmp_expr, "o_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("c_nationkey")
        duckdb$expr_set_alias(tmp_expr, "c_nationkey")
        tmp_expr
      }
    )
  )
  rel53 <- duckdb$rel_set_alias(rel35, "lhs")
  rel54 <- duckdb$rel_set_alias(rel52, "rhs")
  rel55 <- duckdb$rel_project(
    rel53,
    list(
      {
        tmp_expr <- duckdb$expr_reference("l_suppkey")
        duckdb$expr_set_alias(tmp_expr, "l_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_orderkey")
        duckdb$expr_set_alias(tmp_expr, "l_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_extendedprice")
        duckdb$expr_set_alias(tmp_expr, "l_extendedprice")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_discount")
        duckdb$expr_set_alias(tmp_expr, "l_discount")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("s_nationkey")
        duckdb$expr_set_alias(tmp_expr, "s_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_name")
        duckdb$expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_window(duckdb$expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        duckdb$expr_set_alias(tmp_expr, "___row_number_x")
        tmp_expr
      }
    )
  )
  rel56 <- duckdb$rel_project(
    rel54,
    list(
      {
        tmp_expr <- duckdb$expr_reference("o_orderkey")
        duckdb$expr_set_alias(tmp_expr, "o_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("c_nationkey")
        duckdb$expr_set_alias(tmp_expr, "c_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_window(duckdb$expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        duckdb$expr_set_alias(tmp_expr, "___row_number_y")
        tmp_expr
      }
    )
  )
  rel57 <- duckdb$rel_join(
    rel55,
    rel56,
    list(
      duckdb$expr_function(
        "==",
        list(duckdb$expr_reference("l_orderkey", rel55), duckdb$expr_reference("o_orderkey", rel56))
      ),
      duckdb$expr_function(
        "==",
        list(duckdb$expr_reference("s_nationkey", rel55), duckdb$expr_reference("c_nationkey", rel56))
      )
    ),
    "inner"
  )
  rel58 <- duckdb$rel_order(
    rel57,
    list(duckdb$expr_reference("___row_number_x", rel55), duckdb$expr_reference("___row_number_y", rel56))
  )
  rel59 <- duckdb$rel_project(
    rel58,
    list(
      {
        tmp_expr <- duckdb$expr_reference("l_suppkey")
        duckdb$expr_set_alias(tmp_expr, "l_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_function(
          "___coalesce",
          list(duckdb$expr_reference("l_orderkey", rel55), duckdb$expr_reference("o_orderkey", rel56))
        )
        duckdb$expr_set_alias(tmp_expr, "l_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_extendedprice")
        duckdb$expr_set_alias(tmp_expr, "l_extendedprice")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_discount")
        duckdb$expr_set_alias(tmp_expr, "l_discount")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_function(
          "___coalesce",
          list(duckdb$expr_reference("s_nationkey", rel55), duckdb$expr_reference("c_nationkey", rel56))
        )
        duckdb$expr_set_alias(tmp_expr, "s_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_name")
        duckdb$expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      }
    )
  )
  rel60 <- duckdb$rel_project(
    rel59,
    list(
      {
        tmp_expr <- duckdb$expr_reference("l_extendedprice")
        duckdb$expr_set_alias(tmp_expr, "l_extendedprice")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_discount")
        duckdb$expr_set_alias(tmp_expr, "l_discount")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_name")
        duckdb$expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      }
    )
  )
  rel61 <- duckdb$rel_project(
    rel60,
    list(
      {
        tmp_expr <- duckdb$expr_reference("l_extendedprice")
        duckdb$expr_set_alias(tmp_expr, "l_extendedprice")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_discount")
        duckdb$expr_set_alias(tmp_expr, "l_discount")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_name")
        duckdb$expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_function(
          "*",
          list(
            duckdb$expr_reference("l_extendedprice"),
            duckdb$expr_function(
              "-",
              list(
                if ("experimental" %in% names(formals(duckdb$expr_constant))) {
                  duckdb$expr_constant(1, experimental = experimental)
                } else {
                  duckdb$expr_constant(1)
                },
                duckdb$expr_reference("l_discount")
              )
            )
          )
        )
        duckdb$expr_set_alias(tmp_expr, "volume")
        tmp_expr
      }
    )
  )
  rel62 <- duckdb$rel_project(
    rel61,
    list(
      {
        tmp_expr <- duckdb$expr_reference("l_extendedprice")
        duckdb$expr_set_alias(tmp_expr, "l_extendedprice")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_discount")
        duckdb$expr_set_alias(tmp_expr, "l_discount")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_name")
        duckdb$expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("volume")
        duckdb$expr_set_alias(tmp_expr, "volume")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_window(duckdb$expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        duckdb$expr_set_alias(tmp_expr, "___row_number")
        tmp_expr
      }
    )
  )
  rel63 <- duckdb$rel_aggregate(
    rel62,
    groups = list(duckdb$expr_reference("n_name")),
    aggregates = list(
      {
        tmp_expr <- duckdb$expr_function("min", list(duckdb$expr_reference("___row_number")))
        duckdb$expr_set_alias(tmp_expr, "___row_number")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_function("sum", list(duckdb$expr_reference("volume")))
        duckdb$expr_set_alias(tmp_expr, "revenue")
        tmp_expr
      }
    )
  )
  rel64 <- duckdb$rel_order(rel63, list(duckdb$expr_reference("___row_number")))
  rel65 <- duckdb$rel_project(
    rel64,
    list(
      {
        tmp_expr <- duckdb$expr_reference("n_name")
        duckdb$expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("revenue")
        duckdb$expr_set_alias(tmp_expr, "revenue")
        tmp_expr
      }
    )
  )
  rel66 <- duckdb$rel_project(
    rel65,
    list(
      {
        tmp_expr <- duckdb$expr_reference("n_name")
        duckdb$expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("revenue")
        duckdb$expr_set_alias(tmp_expr, "revenue")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_window(duckdb$expr_function("row_number", list()), list(), list(), offset_expr = NULL, default_expr = NULL)
        duckdb$expr_set_alias(tmp_expr, "___row_number")
        tmp_expr
      }
    )
  )
  rel67 <- duckdb$rel_order(rel66, list(duckdb$expr_reference("revenue"), duckdb$expr_reference("___row_number")))
  rel68 <- duckdb$rel_project(
    rel67,
    list(
      {
        tmp_expr <- duckdb$expr_reference("n_name")
        duckdb$expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("revenue")
        duckdb$expr_set_alias(tmp_expr, "revenue")
        tmp_expr
      }
    )
  )
  rel68
  duckdb$rel_to_altrep(rel68)
}
