# Generated by meta_replay_to_fun_file(), do not edit by hand
# nocov start
tpch_raw_21 <- function(con, experimental) {
  df1 <- lineitem
  "count"
  rel1 <- duckdb$rel_from_df(con, df1, experimental = experimental)
  "count"
  rel2 <- duckdb$rel_aggregate(
    rel1,
    groups = list(
      l_orderkey = {
        tmp_expr <- duckdb$expr_reference("l_orderkey")
        duckdb$expr_set_alias(tmp_expr, "l_orderkey")
        tmp_expr
      },
      l_suppkey = {
        tmp_expr <- duckdb$expr_reference("l_suppkey")
        duckdb$expr_set_alias(tmp_expr, "l_suppkey")
        tmp_expr
      }
    ),
    aggregates = list(
      {
        tmp_expr <- duckdb$expr_function("n", list())
        duckdb$expr_set_alias(tmp_expr, "n")
        tmp_expr
      }
    )
  )
  "count"
  rel3 <- duckdb$rel_order(
    rel2,
    list(
      {
        tmp_expr <- duckdb$expr_reference("l_orderkey")
        duckdb$expr_set_alias(tmp_expr, "l_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_suppkey")
        duckdb$expr_set_alias(tmp_expr, "l_suppkey")
        tmp_expr
      }
    )
  )
  "summarise"
  rel4 <- duckdb$rel_aggregate(
    rel3,
    groups = list(duckdb$expr_reference("l_orderkey")),
    aggregates = list(
      {
        tmp_expr <- duckdb$expr_function("n", list())
        duckdb$expr_set_alias(tmp_expr, "n_supplier")
        tmp_expr
      }
    )
  )
  "filter"
  rel5 <- duckdb$rel_filter(
    rel4,
    list(
      duckdb$expr_comparison(
        ">",
        list(
          duckdb$expr_reference("n_supplier"),
          if ("experimental" %in% names(formals(duckdb$expr_constant))) {
            duckdb$expr_constant(1, experimental = experimental)
          } else {
            duckdb$expr_constant(1)
          }
        )
      )
    )
  )
  "semi_join"
  rel6 <- duckdb$rel_from_df(con, df1, experimental = experimental)
  "semi_join"
  rel7 <- duckdb$rel_set_alias(rel6, "lhs")
  "semi_join"
  rel8 <- duckdb$rel_set_alias(rel5, "rhs")
  "semi_join"
  rel9 <- duckdb$rel_join(
    rel7,
    rel8,
    list(
      duckdb$expr_function(
        "==",
        list(duckdb$expr_reference("l_orderkey", rel7), duckdb$expr_reference("l_orderkey", rel8))
      )
    ),
    "semi"
  )
  "inner_join"
  rel10 <- duckdb$rel_set_alias(rel9, "lhs")
  df2 <- orders
  "inner_join"
  rel11 <- duckdb$rel_from_df(con, df2, experimental = experimental)
  "inner_join"
  rel12 <- duckdb$rel_set_alias(rel11, "rhs")
  "inner_join"
  rel13 <- duckdb$rel_join(
    rel10,
    rel12,
    list(
      duckdb$expr_function(
        "==",
        list(duckdb$expr_reference("l_orderkey", rel10), duckdb$expr_reference("o_orderkey", rel12))
      )
    ),
    "inner"
  )
  "inner_join"
  rel14 <- duckdb$rel_project(
    rel13,
    list(
      {
        tmp_expr <- duckdb$expr_function(
          "___coalesce",
          list(duckdb$expr_reference("l_orderkey", rel10), duckdb$expr_reference("o_orderkey", rel12))
        )
        duckdb$expr_set_alias(tmp_expr, "l_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_partkey")
        duckdb$expr_set_alias(tmp_expr, "l_partkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_suppkey")
        duckdb$expr_set_alias(tmp_expr, "l_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_linenumber")
        duckdb$expr_set_alias(tmp_expr, "l_linenumber")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_quantity")
        duckdb$expr_set_alias(tmp_expr, "l_quantity")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_extendedprice")
        duckdb$expr_set_alias(tmp_expr, "l_extendedprice")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_discount")
        duckdb$expr_set_alias(tmp_expr, "l_discount")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_tax")
        duckdb$expr_set_alias(tmp_expr, "l_tax")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_returnflag")
        duckdb$expr_set_alias(tmp_expr, "l_returnflag")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_linestatus")
        duckdb$expr_set_alias(tmp_expr, "l_linestatus")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_shipdate")
        duckdb$expr_set_alias(tmp_expr, "l_shipdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_commitdate")
        duckdb$expr_set_alias(tmp_expr, "l_commitdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_receiptdate")
        duckdb$expr_set_alias(tmp_expr, "l_receiptdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_shipinstruct")
        duckdb$expr_set_alias(tmp_expr, "l_shipinstruct")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_shipmode")
        duckdb$expr_set_alias(tmp_expr, "l_shipmode")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_comment")
        duckdb$expr_set_alias(tmp_expr, "l_comment")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("o_custkey")
        duckdb$expr_set_alias(tmp_expr, "o_custkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("o_orderstatus")
        duckdb$expr_set_alias(tmp_expr, "o_orderstatus")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("o_totalprice")
        duckdb$expr_set_alias(tmp_expr, "o_totalprice")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("o_orderdate")
        duckdb$expr_set_alias(tmp_expr, "o_orderdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("o_orderpriority")
        duckdb$expr_set_alias(tmp_expr, "o_orderpriority")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("o_clerk")
        duckdb$expr_set_alias(tmp_expr, "o_clerk")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("o_shippriority")
        duckdb$expr_set_alias(tmp_expr, "o_shippriority")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("o_comment")
        duckdb$expr_set_alias(tmp_expr, "o_comment")
        tmp_expr
      }
    )
  )
  "filter"
  rel15 <- duckdb$rel_filter(
    rel14,
    list(
      duckdb$expr_comparison(
        "==",
        list(
          duckdb$expr_reference("o_orderstatus"),
          if ("experimental" %in% names(formals(duckdb$expr_constant))) {
            duckdb$expr_constant("F", experimental = experimental)
          } else {
            duckdb$expr_constant("F")
          }
        )
      )
    )
  )
  "summarise"
  rel16 <- duckdb$rel_aggregate(
    rel15,
    groups = list(duckdb$expr_reference("l_orderkey"), duckdb$expr_reference("l_suppkey")),
    aggregates = list(
      {
        tmp_expr <- duckdb$expr_function(
          "any",
          list(
            duckdb$expr_comparison(
              ">",
              list(duckdb$expr_reference("l_receiptdate"), duckdb$expr_reference("l_commitdate"))
            )
          )
        )
        duckdb$expr_set_alias(tmp_expr, "failed_delivery_commit")
        tmp_expr
      }
    )
  )
  "summarise"
  rel17 <- duckdb$rel_aggregate(
    rel16,
    groups = list(duckdb$expr_reference("l_orderkey")),
    aggregates = list(
      {
        tmp_expr <- duckdb$expr_function("n", list())
        duckdb$expr_set_alias(tmp_expr, "n_supplier")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_function(
          "sum",
          list(
            duckdb$expr_function(
              "if_else",
              list(
                duckdb$expr_reference("failed_delivery_commit"),
                if ("experimental" %in% names(formals(duckdb$expr_constant))) {
                  duckdb$expr_constant(1, experimental = experimental)
                } else {
                  duckdb$expr_constant(1)
                },
                if ("experimental" %in% names(formals(duckdb$expr_constant))) {
                  duckdb$expr_constant(0, experimental = experimental)
                } else {
                  duckdb$expr_constant(0)
                }
              )
            )
          )
        )
        duckdb$expr_set_alias(tmp_expr, "num_failed")
        tmp_expr
      }
    )
  )
  "filter"
  rel18 <- duckdb$rel_filter(
    rel17,
    list(
      duckdb$expr_function(
        "&",
        list(
          duckdb$expr_comparison(
            ">",
            list(
              duckdb$expr_reference("n_supplier"),
              if ("experimental" %in% names(formals(duckdb$expr_constant))) {
                duckdb$expr_constant(1, experimental = experimental)
              } else {
                duckdb$expr_constant(1)
              }
            )
          ),
          duckdb$expr_comparison(
            "==",
            list(
              duckdb$expr_reference("num_failed"),
              if ("experimental" %in% names(formals(duckdb$expr_constant))) {
                duckdb$expr_constant(1, experimental = experimental)
              } else {
                duckdb$expr_constant(1)
              }
            )
          )
        )
      )
    )
  )
  "semi_join"
  rel19 <- duckdb$rel_from_df(con, df1, experimental = experimental)
  "semi_join"
  rel20 <- duckdb$rel_set_alias(rel19, "lhs")
  "semi_join"
  rel21 <- duckdb$rel_set_alias(rel18, "rhs")
  "semi_join"
  rel22 <- duckdb$rel_join(
    rel20,
    rel21,
    list(
      duckdb$expr_function(
        "==",
        list(duckdb$expr_reference("l_orderkey", rel20), duckdb$expr_reference("l_orderkey", rel21))
      )
    ),
    "semi"
  )
  df3 <- supplier
  "inner_join"
  rel23 <- duckdb$rel_from_df(con, df3, experimental = experimental)
  "inner_join"
  rel24 <- duckdb$rel_set_alias(rel23, "lhs")
  "inner_join"
  rel25 <- duckdb$rel_set_alias(rel22, "rhs")
  "inner_join"
  rel26 <- duckdb$rel_join(
    rel24,
    rel25,
    list(
      duckdb$expr_function(
        "==",
        list(duckdb$expr_reference("s_suppkey", rel24), duckdb$expr_reference("l_suppkey", rel25))
      )
    ),
    "inner"
  )
  "inner_join"
  rel27 <- duckdb$rel_project(
    rel26,
    list(
      {
        tmp_expr <- duckdb$expr_function(
          "___coalesce",
          list(duckdb$expr_reference("s_suppkey", rel24), duckdb$expr_reference("l_suppkey", rel25))
        )
        duckdb$expr_set_alias(tmp_expr, "s_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("s_name")
        duckdb$expr_set_alias(tmp_expr, "s_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("s_address")
        duckdb$expr_set_alias(tmp_expr, "s_address")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("s_nationkey")
        duckdb$expr_set_alias(tmp_expr, "s_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("s_phone")
        duckdb$expr_set_alias(tmp_expr, "s_phone")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("s_acctbal")
        duckdb$expr_set_alias(tmp_expr, "s_acctbal")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("s_comment")
        duckdb$expr_set_alias(tmp_expr, "s_comment")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_orderkey")
        duckdb$expr_set_alias(tmp_expr, "l_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_partkey")
        duckdb$expr_set_alias(tmp_expr, "l_partkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_linenumber")
        duckdb$expr_set_alias(tmp_expr, "l_linenumber")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_quantity")
        duckdb$expr_set_alias(tmp_expr, "l_quantity")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_extendedprice")
        duckdb$expr_set_alias(tmp_expr, "l_extendedprice")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_discount")
        duckdb$expr_set_alias(tmp_expr, "l_discount")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_tax")
        duckdb$expr_set_alias(tmp_expr, "l_tax")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_returnflag")
        duckdb$expr_set_alias(tmp_expr, "l_returnflag")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_linestatus")
        duckdb$expr_set_alias(tmp_expr, "l_linestatus")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_shipdate")
        duckdb$expr_set_alias(tmp_expr, "l_shipdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_commitdate")
        duckdb$expr_set_alias(tmp_expr, "l_commitdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_receiptdate")
        duckdb$expr_set_alias(tmp_expr, "l_receiptdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_shipinstruct")
        duckdb$expr_set_alias(tmp_expr, "l_shipinstruct")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_shipmode")
        duckdb$expr_set_alias(tmp_expr, "l_shipmode")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_comment")
        duckdb$expr_set_alias(tmp_expr, "l_comment")
        tmp_expr
      }
    )
  )
  "filter"
  rel28 <- duckdb$rel_filter(
    rel27,
    list(
      duckdb$expr_comparison(
        ">",
        list(duckdb$expr_reference("l_receiptdate"), duckdb$expr_reference("l_commitdate"))
      )
    )
  )
  "inner_join"
  rel29 <- duckdb$rel_set_alias(rel28, "lhs")
  df4 <- nation
  "inner_join"
  rel30 <- duckdb$rel_from_df(con, df4, experimental = experimental)
  "inner_join"
  rel31 <- duckdb$rel_set_alias(rel30, "rhs")
  "inner_join"
  rel32 <- duckdb$rel_join(
    rel29,
    rel31,
    list(
      duckdb$expr_function(
        "==",
        list(duckdb$expr_reference("s_nationkey", rel29), duckdb$expr_reference("n_nationkey", rel31))
      )
    ),
    "inner"
  )
  "inner_join"
  rel33 <- duckdb$rel_project(
    rel32,
    list(
      {
        tmp_expr <- duckdb$expr_reference("s_suppkey")
        duckdb$expr_set_alias(tmp_expr, "s_suppkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("s_name")
        duckdb$expr_set_alias(tmp_expr, "s_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("s_address")
        duckdb$expr_set_alias(tmp_expr, "s_address")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_function(
          "___coalesce",
          list(duckdb$expr_reference("s_nationkey", rel29), duckdb$expr_reference("n_nationkey", rel31))
        )
        duckdb$expr_set_alias(tmp_expr, "s_nationkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("s_phone")
        duckdb$expr_set_alias(tmp_expr, "s_phone")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("s_acctbal")
        duckdb$expr_set_alias(tmp_expr, "s_acctbal")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("s_comment")
        duckdb$expr_set_alias(tmp_expr, "s_comment")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_orderkey")
        duckdb$expr_set_alias(tmp_expr, "l_orderkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_partkey")
        duckdb$expr_set_alias(tmp_expr, "l_partkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_linenumber")
        duckdb$expr_set_alias(tmp_expr, "l_linenumber")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_quantity")
        duckdb$expr_set_alias(tmp_expr, "l_quantity")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_extendedprice")
        duckdb$expr_set_alias(tmp_expr, "l_extendedprice")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_discount")
        duckdb$expr_set_alias(tmp_expr, "l_discount")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_tax")
        duckdb$expr_set_alias(tmp_expr, "l_tax")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_returnflag")
        duckdb$expr_set_alias(tmp_expr, "l_returnflag")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_linestatus")
        duckdb$expr_set_alias(tmp_expr, "l_linestatus")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_shipdate")
        duckdb$expr_set_alias(tmp_expr, "l_shipdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_commitdate")
        duckdb$expr_set_alias(tmp_expr, "l_commitdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_receiptdate")
        duckdb$expr_set_alias(tmp_expr, "l_receiptdate")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_shipinstruct")
        duckdb$expr_set_alias(tmp_expr, "l_shipinstruct")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_shipmode")
        duckdb$expr_set_alias(tmp_expr, "l_shipmode")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("l_comment")
        duckdb$expr_set_alias(tmp_expr, "l_comment")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_name")
        duckdb$expr_set_alias(tmp_expr, "n_name")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_regionkey")
        duckdb$expr_set_alias(tmp_expr, "n_regionkey")
        tmp_expr
      },
      {
        tmp_expr <- duckdb$expr_reference("n_comment")
        duckdb$expr_set_alias(tmp_expr, "n_comment")
        tmp_expr
      }
    )
  )
  "filter"
  rel34 <- duckdb$rel_filter(
    rel33,
    list(
      duckdb$expr_comparison(
        "==",
        list(
          duckdb$expr_reference("n_name"),
          if ("experimental" %in% names(formals(duckdb$expr_constant))) {
            duckdb$expr_constant("SAUDI ARABIA", experimental = experimental)
          } else {
            duckdb$expr_constant("SAUDI ARABIA")
          }
        )
      )
    )
  )
  "summarise"
  rel35 <- duckdb$rel_aggregate(
    rel34,
    groups = list(duckdb$expr_reference("s_name")),
    aggregates = list(
      {
        tmp_expr <- duckdb$expr_function("n", list())
        duckdb$expr_set_alias(tmp_expr, "numwait")
        tmp_expr
      }
    )
  )
  "arrange"
  rel36 <- duckdb$rel_order(rel35, list(duckdb$expr_reference("numwait"), duckdb$expr_reference("s_name")))
  "head"
  rel37 <- duckdb$rel_limit(rel36, 100)
  rel37
  duckdb$rel_to_altrep(rel37)
}
# nocov end
