# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr ungroup
#' @export
ungroup.duckplyr_df <- function(x, ...) {
  # dplyr forward
  x_df <- x
  class(x_df) <- setdiff(class(x_df), "duckplyr_df")
  out <- ungroup(x_df, ...)
  out <- dplyr_reconstruct(out, x)
  return(out)

  # dplyr implementation
  check_dots_empty()
  x
}

duckplyr_ungroup <- function(x, ...) {
  try_fetch(
    x <- as_duckplyr_df(x),
    error = function(e) {
      testthat::skip(conditionMessage(e))
    }
  )
  out <- ungroup(x, ...)
  class(out) <- setdiff(class(out), "duckplyr_df")
  out
}
