# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr ungroup
#' @export
ungroup.duckplyr_df <- function(x, ...) {
  # Our implementation
  force(x)
  out <- NextMethod()
  out <- dplyr_reconstruct(out, x)
  return(out)
}
