# Generated by 02-duckplyr_df-methods.R
#' @importFrom dplyr union_all
#' @export
union_all.duckplyr_df <- function(x, y, ...) {
  # Our implementation
  force(x)
  out <- NextMethod()
  out <- dplyr_reconstruct(out, x)
  return(out)

  # dplyr implementation
  check_dots_empty()
  check_compatible(x, y)

  out <- vec_rbind(x, y)
  dplyr_reconstruct(out, x)
}
