name: Test (Receive)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      # Directories with source code and benchmarking code
      - "R/**"
      - "touchstone/**"
      # Benchmarking config file
      - ".github/workflows/test-*.yaml"
      # Package metadata
      - DESCRIPTION

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          echo "Hello, world!"
        shell: bash
