name: Continuous Benchmarks (Comment)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["Continuous Benchmarks (Receive)"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: lorenzwalthert/touchstone/actions/comment@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
